/* TGM Studio 3D — dependency-free WebGL renderer and parametric reference garments.
   All geometry is for visualization; no sewing solver or physical fit prediction. */
const PRO_DEFAULTS={fit:'regular',length:100,sleeve:100,folds:42,roughness:78,mannequin:false,lighting:'soft',background:'light',workspace:'3d',view:'perspective'};
const PRO_FITS={regular:1,relaxed:1.09,oversize:1.2};
const v3=(x=0,y=0,z=0)=>[x,y,z],add3=(a,b)=>a.map((v,i)=>v+b[i]),sub3=(a,b)=>a.map((v,i)=>v-b[i]),mul3=(a,s)=>a.map(v=>v*s),dot3=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross3=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm3=a=>{const d=Math.hypot(...a)||1;return a.map(v=>v/d)},lerp=(a,b,t)=>a+(b-a)*t;
function multiply4(a,b){const out=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)out[c*4+r]+=a[k*4+r]*b[c*4+k];return out}
function perspective4(fov,aspect,near,far){const f=1/Math.tan(fov/2),m=new Float32Array(16);m[0]=f/aspect;m[5]=f;m[10]=(far+near)/(near-far);m[11]=-1;m[14]=2*far*near/(near-far);return m}
function lookAt4(eye,target){const z=norm3(sub3(eye,target)),x=norm3(cross3([0,1,0],z)),y=cross3(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot3(x,eye),-dot3(y,eye),-dot3(z,eye),1])}
class GarmentMesh{
 constructor(name,material='front',rib=false){this.name=name;this.material=material;this.rib=rib;this.positions=[];this.normals=[];this.uvs=[];this.indices=[]}
 addVertex(p,uv){this.positions.push(...p);this.uvs.push(...uv);return this.positions.length/3-1}
 triangle(a,b,c){this.indices.push(a,b,c)}
 finish(){const p=this.positions,n=new Float32Array(p.length);for(let i=0;i<this.indices.length;i+=3){const [a,b,c]=this.indices.slice(i,i+3).map(v=>v*3),normal=cross3([p[b]-p[a],p[b+1]-p[a+1],p[b+2]-p[a+2]],[p[c]-p[a],p[c+1]-p[a+1],p[c+2]-p[a+2]]);for(const j of[a,b,c])for(let k=0;k<3;k++)n[j+k]+=normal[k]}for(let i=0;i<n.length;i+=3){const a=norm3([n[i],n[i+1],n[i+2]]);n.set(a,i)}this.normals=Array.from(n);return this}
}
function surfaceMesh(name,material,nu,nv,fn,rib=false,reverse=false){const mesh=new GarmentMesh(name,material,rib);for(let j=0;j<=nv;j++)for(let i=0;i<=nu;i++){const value=fn(i/nu,j/nv);mesh.addVertex(value.p,value.uv||[i/nu,j/nv])}for(let j=0;j<nv;j++)for(let i=0;i<nu;i++){const a=j*(nu+1)+i,b=a+1,c=a+nu+1,d=c+1;if(reverse){mesh.triangle(a,d,b);mesh.triangle(a,c,d)}else{mesh.triangle(a,b,d);mesh.triangle(a,d,c)}}return mesh.finish()}
function tubeMesh(name,material,points,radius,segments=12,rib=false){return surfaceMesh(name,material,segments,points.length-1,(u,v)=>{const idx=Math.round(v*(points.length-1)),point=points[idx],tangent=norm3(sub3(points[Math.min(idx+1,points.length-1)],points[Math.max(0,idx-1)])),up=Math.abs(tangent[1])>.96?[1,0,0]:[0,1,0],a=norm3(cross3(tangent,up)),b=cross3(tangent,a),theta=u*Math.PI*2;return {p:add3(point,add3(mul3(a,Math.cos(theta)*radius),mul3(b,Math.sin(theta)*radius))),uv:[u,v]};},rib)}
function ellipseMesh(name,material,center,radii){return surfaceMesh(name,material,32,20,(u,v)=>{const theta=u*Math.PI*2,phi=.002+v*(Math.PI-.004);return {p:[center[0]+radii[0]*Math.sin(phi)*Math.cos(theta),center[1]+radii[1]*Math.cos(phi),center[2]+radii[2]*Math.sin(phi)*Math.sin(theta)]}})}
function garmentGeometry(order){const p={...PRO_DEFAULTS,...order.pro},fit=PRO_FITS[p.fit],sleeveless=order.garment==='sleeveless',zip=order.garment==='zipneck',hood=order.garment==='hoodie',longSleeve=hood||zip,length=(sleeveless?.82:1)*p.length/100,fold=p.folds/100,mesh=[],bottom=-1.03*length,upper=.87,neckY=1.28,bodyWidth=.67*fit;
 const angle=(u,back)=>u*Math.PI+(back?Math.PI:0);
 const bodyAt=(theta,y)=>{const v=clamp((y-bottom)/(upper-bottom),0,1),radius=bodyWidth*(.945+.025*Math.cos(v*Math.PI*2)+.027*v),depth=(hood?.34:.305)*fit*(.97+.03*Math.cos(v*Math.PI));let x=radius*Math.cos(theta),z=depth*Math.sin(theta);const sin=Math.sin(theta),amp=fold*.028*Math.pow(Math.abs(sin),1.5);const wave=amp*(Math.sin(theta*13+y*4)*.7+Math.sin(theta*23-y*3)*.32+Math.sin(y*14+theta*4)*.35);z+=Math.sign(sin)*wave*(.25+.75*Math.pow(1-v,.6));return [x,y+.22*Math.pow(Math.abs(Math.cos(theta)),2)*Math.pow(v,4),z]};
 const sheetUV=(point,back)=>[(400+(back?-1:1)*point[0]/bodyWidth*168)/800,(155+(neckY-point[1])/(neckY-bottom)*599)/920];
 for(const back of[false,true]){
  const mat=back?'back':'front';mesh.push(surfaceMesh('Cuerpo '+mat,mat,64,58,(u,v)=>{const point=bodyAt(angle(u,back),lerp(bottom,upper,v));return {p:point,uv:sheetUV(point,back)}}));
  mesh.push(surfaceMesh('Hombros '+mat,mat,64,24,(u,v)=>{const theta=angle(u,back),outer=bodyAt(theta,upper),neckRadiusX=.263,neckRadiusZ=.188,front=Math.max(0,Math.sin(theta));const lower=order.neck==='v'?.255*(1-Math.abs(Math.cos(theta)))*(front>0?1:0):.112*Math.pow(front,1.5);const inner=[neckRadiusX*Math.cos(theta),neckY-lower,.065+neckRadiusZ*Math.sin(theta)];let point=outer.map((a,i)=>lerp(a,inner[i],i===1?v:v*v));point[2]+=Math.sin(v*Math.PI)*.035*Math.sin(theta);return {p:point,uv:sheetUV(point,back)}}));
  if(order.hem==='rib'||order.contrast.hem){mesh.push(surfaceMesh('Pretina '+mat,order.contrast.hem?'contrast':'body',64,6,(u,v)=>{const point=bodyAt(angle(u,back),lerp(bottom+.006,bottom+(order.hem==='rib'?.115:.047),v));point[0]*=1.008;point[2]*=1.022;return {p:point,uv:[u*4,v]};},order.hem==='rib'))}
  const seam=[];for(let i=0;i<=70;i++){const q=bodyAt(angle(i/70,back),bottom+.03);q[0]*=1.01;q[2]*=1.024;seam.push(q)}mesh.push(tubeMesh('Costura inferior '+mat,'seam',seam,.0018,5));
 }
 // Overlapping tubular sleeve roots create a continuous visual shoulder volume.
 if(!sleeveless){for(const side of[-1,1]){const sleeveLength=(longSleeve?2.0:.62)*p.sleeve/100,axis=norm3([side*(longSleeve?.58:.87),longSleeve?-.82:-.49,0]),origin=[side*(longSleeve?.40:.46)*fit,longSleeve?.85:.81,0],sideVec=[-axis[1]*side,axis[0]*side,0];
  const sleeveAt=(theta,t,extra=0)=>{const center=add3(origin,mul3(axis,sleeveLength*t)),r=lerp(.285*fit,longSleeve?.135:.22*fit,t)+extra;const wrinkle=fold*.004*Math.sin(t*22+theta*3)*Math.sin(t*Math.PI);return add3(center,add3(mul3(sideVec,Math.cos(theta)*(r+wrinkle)),[0,0,Math.sin(theta)*(r*.89+wrinkle)]))};
  for(const back of[false,true]){mesh.push(surfaceMesh('Manga '+side+' '+back,back?'back':'front',40,longSleeve?40:24,(u,v)=>{const theta=angle(u,back),point=sleeveAt(theta,v),sourceX=side>0?lerp(567,longSleeve?687:677,v):lerp(233,longSleeve?113:123,v),sourceY=lerp(215,longSleeve?733:295,v),offset=-Math.cos(theta)*(longSleeve?55:57);return {p:point,uv:[(back?800-sourceX:sourceX)/800,(sourceY+offset)/920]}}));
   if(order.cuff==='rib'||order.contrast.cuff){mesh.push(surfaceMesh('Puño '+side+' '+back,order.contrast.cuff?'contrast':'body',40,6,(u,v)=>({p:sleeveAt(angle(u,back),lerp(order.cuff==='rib'?.87:.93,1,v),.002),uv:[u*3,v]}),order.cuff==='rib'))}
   const line=[];for(let i=0;i<=45;i++)line.push(sleeveAt(angle(i/45,back),.965,.005));mesh.push(tubeMesh('Costura puño '+side+' '+back,'seam',line,.0019,5));
  }
 }}
 const neckMaterial=order.contrast.neck?'contrast':'body';
 if(!hood){mesh.push(surfaceMesh('Cuello',neckMaterial,80,7,(u,v)=>{const theta=u*Math.PI*2,front=Math.max(0,Math.sin(theta)),lower=order.neck==='v'?.255*(1-Math.abs(Math.cos(theta)))*(front>0?1:0):zip?0:.112*Math.pow(front,1.5);return {p:[(.263+.045*v)*Math.cos(theta),neckY-lower+(zip?.06:0)-.03*v+.005,.065+(.188+.04*v)*Math.sin(theta)],uv:[u*5,v]}},order.garment!=='polo'&&!zip))}
 if(zip){mesh.push(surfaceMesh('Cierre',neckMaterial,2,16,(u,v)=>({p:[lerp(-.02,.02,u),lerp(1.18,.70,v),.328],uv:[u,v]})));mesh.push(surfaceMesh('Dientes cierre','metal',2,16,(u,v)=>({p:[lerp(-.006,.006,u),lerp(1.17,.71,v),.336],uv:[u,v]})));mesh.push(ellipseMesh('Tirador','metal',[0,.72,.348],[.013,.02,.008]));}
 if(order.garment==='polo'){
  for(const side of[-1,1]){mesh.push(surfaceMesh('Solapa '+side,neckMaterial,15,12,(u,v)=>{const x=side*lerp(.07,.30,u),top=neckY-.12+.06*u,y=top-v*(.27+.02*u),z=.275+v*.06;return {p:[x+side*v*.052,y,z],uv:[u,v]}}))}
  mesh.push(surfaceMesh('Cartera',neckMaterial,2,15,(u,v)=>({p:[lerp(-.047,.047,u),lerp(1.11,.61,v),.331],uv:[u,v]})));
  for(const y of[1.03,.86,.69])mesh.push(ellipseMesh('Botón','button',[0,y,.344],[.014,.014,.007]));
 }
 if(hood){
  mesh.push(surfaceMesh('Capucha',neckMaterial,80,32,(u,v)=>{const theta=u*Math.PI*2,phi=v*(Math.PI/2-.007),r=Math.cos(phi);return {p:[.453*r*Math.cos(theta),1.655+.553*r*Math.sin(theta),.19-.70*Math.sin(phi)],uv:[u,v]}}));
  const hoodRim=[];for(let i=0;i<=90;i++){const t=i/90*Math.PI*2;hoodRim.push([.453*Math.cos(t),1.655+.553*Math.sin(t),.19])}mesh.push(tubeMesh('Borde capucha',neckMaterial,hoodRim,.013,8));
  if(order.hood.pocket){mesh.push(surfaceMesh('Bolsillo','front',30,20,(u,v)=>{const yy=lerp(bottom+.32,bottom+.77,v),half=lerp(.45,.315,v),xx=(u*2-1)*half;const theta=Math.acos(clamp(xx/bodyWidth,-1,1)),body=bodyAt(theta,yy);const point=[xx,yy,body[2]+.021+Math.sin(u*Math.PI)*.014];return {p:point,uv:sheetUV(point,false)}}));for(const side of[-1,1]){const lip=[];for(let i=0;i<=20;i++){const t=i/20,yy=lerp(bottom+.35,bottom+.74,t),xx=side*lerp(.44,.32,t),q=bodyAt(Math.acos(xx/bodyWidth),yy);lip.push([xx,yy,q[2]+.035])}mesh.push(tubeMesh('Entrada bolsillo '+side,'seam',lip,.004,6))}}
  if(order.hood.drawstring){for(const side of[-1,1]){const cord=[];for(let i=0;i<=32;i++){const t=i/32;cord.push([side*(.19+.014*Math.sin(t*6)),1.155-t*.48,.23+.09*Math.sin(t*Math.PI/2)])}mesh.push(tubeMesh('Cordón '+side,'cord',cord,.008,8));const end=cord.at(-1);mesh.push(tubeMesh('Punta cordón '+side,'metal',[end,add3(end,[.002,-.045,.003])],.009,8))}}
 }
 if(p.mannequin){mesh.push(ellipseMesh('Torso de referencia','mannequin',[0,.025,-.015],[.52,1.16,.24]));mesh.push(ellipseMesh('Cuello de referencia','mannequin',[0,1.28,0],[.155,.25,.14]));mesh.push(ellipseMesh('Cabeza de referencia','mannequin',[0,1.82,-.028],[.22,.325,.218]));for(const side of[-1,1]){const arm=[];for(let i=0;i<=20;i++){const t=i/20;arm.push([side*(.44+t*(hood?1.12:1.22)),.68-t*(hood?1.63:.69),0])}mesh.push(tubeMesh('Brazo de referencia '+side,'mannequin',arm,.10,18))}}
 for(const m of mesh){const flip=m.name.startsWith('Cuerpo ')||m.name.startsWith('Hombros ')||m.name.startsWith('Pretina ')||m.name.startsWith('Manga -1')||m.name.startsWith('Puño -1')||m.name==='Capucha'||m.name==='Cartera'||m.name==='Solapa 1'||m.name==='Cierre';if(flip){for(let i=0;i<m.indices.length;i+=3)[m.indices[i+1],m.indices[i+2]]=[m.indices[i+2],m.indices[i+1]];m.normals=m.normals.map(n=>-n)}}const joins=new Map();for(const m of mesh.filter(m=>/^(Cuerpo|Hombros) /.test(m.name))){for(let i=0;i<m.positions.length;i+=3){const key=m.positions.slice(i,i+3).map(x=>x.toFixed(5)).join(',');if(!joins.has(key))joins.set(key,[]);joins.get(key).push([m,i])}}for(const entries of joins.values()){if(entries.length<2)continue;const sum=entries.reduce((a,[m,i])=>add3(a,m.normals.slice(i,i+3)),[0,0,0]),n=norm3(sum);for(const [m,i]of entries)m.normals.splice(i,3,...n)}return mesh;
}
const STUDIO_VERTEX=`attribute vec3 aPosition;attribute vec3 aNormal;attribute vec2 aUv;uniform mat4 uMVP;varying vec3 vPosition;varying vec3 vNormal;varying vec2 vUv;void main(){vPosition=aPosition;vNormal=aNormal;vUv=aUv;gl_Position=uMVP*vec4(aPosition,1.0);}`;
const STUDIO_FRAGMENT=`precision highp float;varying vec3 vPosition;varying vec3 vNormal;varying vec2 vUv;uniform sampler2D uTexture;uniform vec3 uColor;uniform vec3 uEye;uniform vec3 uLight;uniform float uTextured;uniform float uRoughness;uniform float uRib;uniform float uFabric;uniform float uLighting;void main(){vec3 n=normalize(vNormal);if(!gl_FrontFacing)n=-n;vec3 base=mix(uColor,texture2D(uTexture,vUv).rgb,uTextured);float grain=0.0;if(uRib>0.5){grain=sin(vUv.x*520.0)*0.035;}else if(uFabric>0.5&&uFabric<1.5){grain=sin(vUv.x*1450.0+sin(vUv.y*1700.0))*0.012;}else if(uFabric<2.5&&uFabric>1.5){grain=sin(vUv.x*1000.0)*sin(vUv.y*1000.0)*0.028;}else if(uFabric>2.5){grain=sin(vUv.x*2200.0)*sin(vUv.y*1940.0)*0.009;}base*=1.0+grain;vec3 light=normalize(uLight);vec3 view=normalize(uEye-vPosition);vec3 halfV=normalize(light+view);float key=max(dot(n,light),0.0);float fill=max(dot(n,normalize(vec3(-1.0,.5,-.8))),0.0);float rim=pow(1.0-max(dot(n,view),0.0),3.0);float shine=pow(max(dot(n,halfV),0.0),mix(100.0,12.0,uRoughness))*(1.0-uRoughness)*.30;float ao=.92+.08*clamp(vPosition.y+.7,0.0,1.0);float inside=gl_FrontFacing?1.0:.62;vec3 rgb=(base*(.35+key*.59+fill*.20)+vec3(shine)+base*rim*.07)*ao*inside;if(uLighting>1.5)rgb=(base*(.20+key*.76+fill*.13)+vec3(shine))*inside;gl_FragColor=vec4(clamp(rgb,0.0,1.0),1.0);}`;
class StudioRenderer{
 constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl',{alpha:true,antialias:true,preserveDrawingBuffer:true,premultipliedAlpha:false});if(!this.gl)throw Error('Este navegador no tiene 3D disponible. Puedes seguir trabajando en la vista 2D.');this.meshes=[];this.yaw=.42;this.pitch=.04;this.distance=5.3;this.pan=[0,0];this.pendingFrame=0;this.textureRevision=0;this.spinning=false;this.lastTime=0;this.buildProgram();this.frontTexture=this.createTexture();this.backTexture=this.createTexture();this.whiteTexture=this.createTexture();this.configureInput();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas);this.canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.lost=true;this.spinning=false;toast('La vista 3D se pausó. Guarda el JSON y recarga la app para recuperarla.')});this.canvas.addEventListener('webglcontextrestored',()=>{this.lost=false;this.buildProgram();this.frontTexture=this.createTexture();this.backTexture=this.createTexture();this.whiteTexture=this.createTexture();this.geometryKey=null;this.meshes=[];this.rebuild();scheduleRender()})}
 buildProgram(){const g=this.gl;const shader=(type,source)=>{const s=g.createShader(type);g.shaderSource(s,source);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS))throw Error('No se pudo iniciar el render 3D: '+g.getShaderInfoLog(s));return s};const vs=shader(g.VERTEX_SHADER,STUDIO_VERTEX),fs=shader(g.FRAGMENT_SHADER,STUDIO_FRAGMENT),program=g.createProgram();g.attachShader(program,vs);g.attachShader(program,fs);g.linkProgram(program);g.deleteShader(vs);g.deleteShader(fs);if(!g.getProgramParameter(program,g.LINK_STATUS))throw Error('El render 3D no pudo iniciarse.');this.program=program;this.locations={};for(const name of['aPosition','aNormal','aUv'])this.locations[name]=g.getAttribLocation(program,name);for(const name of['uMVP','uTexture','uColor','uEye','uLight','uTextured','uRoughness','uRib','uFabric','uLighting'])this.locations[name]=g.getUniformLocation(program,name);g.enable(g.DEPTH_TEST);g.depthFunc(g.LEQUAL);g.disable(g.CULL_FACE)}
 createTexture(){const g=this.gl,t=g.createTexture();g.bindTexture(g.TEXTURE_2D,t);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,1,1,0,g.RGBA,g.UNSIGNED_BYTE,new Uint8Array([255,255,255,255]));g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);return t}
 setTexture(texture,canvas){const g=this.gl;g.bindTexture(g.TEXTURE_2D,texture);g.pixelStorei(g.UNPACK_FLIP_Y_WEBGL,false);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,g.RGBA,g.UNSIGNED_BYTE,canvas)}
 rebuild(){if(this.lost)return;const key=JSON.stringify([state.garment,state.neck,state.cuff,state.hem,state.contrast,state.hood,state.pro.fit,state.pro.length,state.pro.sleeve,state.pro.folds,state.pro.mannequin]);if(key===this.geometryKey)return;this.geometryKey=key;const gl=this.gl;for(const m of this.meshes)for(const b of[m.pos,m.normal,m.uv,m.index])gl.deleteBuffer(b);const data=garmentGeometry(state);let minY=Infinity,maxY=-Infinity,minX=Infinity,maxX=-Infinity;for(const m of data)for(let i=0;i<m.positions.length;i+=3){minX=Math.min(minX,m.positions[i]);maxX=Math.max(maxX,m.positions[i]);minY=Math.min(minY,m.positions[i+1]);maxY=Math.max(maxY,m.positions[i+1])}this.centerY=(minY+maxY)/2;this.frameScale=Math.max(1,(maxY-minY)/2.35,(maxX-minX)/2.25);this.meshes=data.map(mesh=>{const buffer=(values,type,target)=>{const b=gl.createBuffer();gl.bindBuffer(target,b);gl.bufferData(target,new type(values),gl.STATIC_DRAW);return b};return {...mesh,pos:buffer(mesh.positions,Float32Array,gl.ARRAY_BUFFER),normal:buffer(mesh.normals,Float32Array,gl.ARRAY_BUFFER),uv:buffer(mesh.uvs,Float32Array,gl.ARRAY_BUFFER),index:buffer(mesh.indices,Uint16Array,gl.ELEMENT_ARRAY_BUFFER)}});this.render()}
 async updateTextures(){if(this.lost)return;const revision=++this.textureRevision;const textures=[];for(const view of['front','back']){const c=document.createElement('canvas');c.width=1600;c.height=1840;const ctx=c.getContext('2d');ctx.scale(2,2);ctx.fillStyle=state.bodyColor;ctx.fillRect(0,0,W,H);for(const a of state.artworks.filter(a=>a.view===view))await drawArt(ctx,a);textures.push(c)}if(revision!==this.textureRevision)return;this.setTexture(this.frontTexture,textures[0]);this.setTexture(this.backTexture,textures[1]);this.rebuild();this.render()}
 resize(){const rect=this.canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;const dpr=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.round(rect.width*dpr);this.canvas.height=Math.round(rect.height*dpr);this.render()}
 camera(width=this.canvas.width,height=this.canvas.height){const focus=this.centerY??.15,dist=this.distance*(this.frameScale||1)*Math.max(1,.85/(width/height));const target=[this.pan[0],focus+this.pan[1],0],eye=[target[0]+Math.sin(this.yaw)*Math.cos(this.pitch)*dist,target[1]+Math.sin(this.pitch)*dist,target[2]+Math.cos(this.yaw)*Math.cos(this.pitch)*dist];const projection=perspective4(37*Math.PI/180,width/height,.1,50),view=lookAt4(eye,target);return {eye,mvp:multiply4(projection,view)}}
 render(){if(this.lost||!this.program)return;const gl=this.gl,L=this.locations,c=this.camera();gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(this.program);gl.uniformMatrix4fv(L.uMVP,false,c.mvp);gl.uniform3fv(L.uEye,c.eye);const p=state.pro,light=p.lighting==='side'?[-2,1.8,2.4]:p.lighting==='dramatic'?[-1.7,3,1.8]:[-2,3,4];gl.uniform3fv(L.uLight,light);gl.uniform1f(L.uLighting,p.lighting==='dramatic'?2:0);gl.uniform1i(L.uTexture,0);gl.activeTexture(gl.TEXTURE0);for(const m of this.meshes){for(const [attr,b,size]of[['aPosition',m.pos,3],['aNormal',m.normal,3],['aUv',m.uv,2]]){gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.enableVertexAttribArray(L[attr]);gl.vertexAttribPointer(L[attr],size,gl.FLOAT,false,0,0)}const text=m.material==='front'||m.material==='back';gl.bindTexture(gl.TEXTURE_2D,m.material==='front'?this.frontTexture:m.material==='back'?this.backTexture:this.whiteTexture);let color=state.bodyColor;if(m.material==='contrast')color=state.contrastColor;if(m.material==='seam')color=state.bodyColor;if(m.material==='cord')color='#dfdfd8';if(m.material==='button')color='#e0e1df';if(m.material==='metal')color='#959fa5';if(m.material==='mannequin')color='#858b92';gl.uniform3fv(L.uColor,parseColor(color).map(v=>v/255));gl.uniform1f(L.uTextured,text?1:0);gl.uniform1f(L.uRoughness,m.material==='metal'?.25:p.roughness/100);gl.uniform1f(L.uRib,m.rib?1:0);gl.uniform1f(L.uFabric,['mannequin','cord','button','metal'].includes(m.material)?0:({smooth:0,jersey:1,pique:2,fleece:3}[state.texture]));gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,m.index);gl.drawElements(gl.TRIANGLES,m.indices.length,gl.UNSIGNED_SHORT,0)}if($('#cameraLabel'))$('#cameraLabel').textContent='Giro '+Math.round(((this.yaw*180/Math.PI)%360+360)%360)+'°';}
 preset(view){const values={front:0,back:Math.PI,left:Math.PI/2,right:-Math.PI/2,perspective:.42};this.yaw=values[view]??.42;this.pitch=view==='perspective'?.045:0;this.pan=[0,0];this.distance=5.3;this.render()}
 configureInput(){const canvas=this.canvas,pointers=new Map();let last=null,pinch=null;canvas.addEventListener('pointerdown',e=>{canvas.focus();pointers.set(e.pointerId,[e.clientX,e.clientY]);canvas.setPointerCapture(e.pointerId);last=[e.clientX,e.clientY];if(pointers.size===2){const a=[...pointers.values()];pinch=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1])}canvas.classList.add('orbiting')});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const a=[...pointers.values()],distance=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);if(pinch&&distance)this.distance=clamp(this.distance*pinch/distance,3.2,10);pinch=distance}else if(last){const dx=e.clientX-last[0],dy=e.clientY-last[1];if(e.shiftKey||e.buttons===2){this.pan[0]-=dx*.003;this.pan[1]+=dy*.003}else{this.yaw-=dx*.008;this.pitch=clamp(this.pitch+dy*.006,-.85,.85)}}last=[e.clientX,e.clientY];this.render()});const finish=e=>{pointers.delete(e.pointerId);pinch=null;last=null;canvas.classList.remove('orbiting')};canvas.addEventListener('pointerup',finish);canvas.addEventListener('pointercancel',finish);canvas.addEventListener('lostpointercapture',finish);canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{e.preventDefault();this.distance=clamp(this.distance*Math.exp(e.deltaY*.001),3.2,10);this.render()},{passive:false});canvas.addEventListener('keydown',e=>{const action={ArrowLeft:()=>this.yaw-=.1,ArrowRight:()=>this.yaw+=.1,ArrowUp:()=>this.pitch=clamp(this.pitch+.1,-.85,.85),ArrowDown:()=>this.pitch=clamp(this.pitch-.1,-.85,.85),'+':()=>this.distance=Math.max(3.2,this.distance-.3),'-':()=>this.distance=Math.min(10,this.distance+.3),Home:()=>this.preset('perspective')}[e.key];if(action){e.preventDefault();action();this.render()}})}
 toggleSpin(){this.spinning=!this.spinning;$('#spin3d').setAttribute('aria-pressed',this.spinning);const tick=time=>{if(!this.spinning)return;if(!document.hidden){this.yaw+=(Math.min(time-(this.lastTime||time),40))*.00025;this.render()}this.lastTime=time;requestAnimationFrame(tick)};if(this.spinning){this.lastTime=0;requestAnimationFrame(tick)}}
 async capture(view,current=false){if(this.lost||this.gl.isContextLost())throw Error('La vista 3D está pausada. Guarda el JSON y recarga antes de exportar.');await this.updateTextures();const old={yaw:this.yaw,pitch:this.pitch,distance:this.distance,pan:[...this.pan],w:this.canvas.width,h:this.canvas.height},spinning=this.spinning;this.spinning=false;try{if(!current)this.preset(view);this.canvas.width=2000;this.canvas.height=2300;this.render();if(this.gl.isContextLost())throw Error('No se pudo completar el render 3D. Guarda el pedido y recarga la app.');const c=document.createElement('canvas');c.width=2000;c.height=2300;const ctx=c.getContext('2d');const bg=ctx.createRadialGradient(950,600,100,1000,1100,1700);bg.addColorStop(0,'#ffffff');bg.addColorStop(1,'#e4e8ed');ctx.fillStyle=bg;ctx.fillRect(0,0,c.width,c.height);ctx.save();ctx.translate(1000,2000);ctx.scale(1,.14);const shadow=ctx.createRadialGradient(0,0,20,0,0,500);shadow.addColorStop(0,'#23314a25');shadow.addColorStop(1,'#23314a00');ctx.fillStyle=shadow;ctx.beginPath();ctx.arc(0,0,500,0,Math.PI*2);ctx.fill();ctx.restore();ctx.drawImage(this.canvas,0,0);return c}finally{this.yaw=old.yaw;this.pitch=old.pitch;this.distance=old.distance;this.pan=old.pan;this.canvas.width=old.w;this.canvas.height=old.h;this.render();if(spinning){this.spinning=false;this.toggleSpin()}}}
}
let studio=null,studioInitAttempted=false;
function ensurePro(){state.pro={...PRO_DEFAULTS,...state.pro}}
function syncProUI(){ensurePro();$$('[data-pro]').forEach(el=>{const value=state.pro[el.dataset.pro];if(el.type==='checkbox')el.checked=value;else el.value=value});for(const k of['length','sleeve','folds','roughness'])if($('#pro-'+k+'-value'))$('#pro-'+k+'-value').textContent=state.pro[k]+' %';$('#proFitLabel').textContent=({regular:'Regular',relaxed:'Relajada',oversize:'Oversize'}[state.pro.fit]);$('#studioStage').dataset.background=state.pro.background;setWorkspace(state.pro.workspace,false);if(studio){studio.rebuild();studio.render()}}
function setWorkspace(mode,save=true){state.pro.workspace=mode;$('#proWorkspace').dataset.mode=mode;$$('[data-workspace]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.workspace===mode));if(studio)requestAnimationFrame(()=>studio.resize());if(save)changed()}
function initPro(){ensurePro();if(studioInitAttempted)return;studioInitAttempted=true;for(const b of $$('[data-workspace]'))b.addEventListener('click',()=>setWorkspace(b.dataset.workspace));$$('[data-pro]').forEach(el=>el.addEventListener(el.type==='range'?'input':'change',()=>{state.pro[el.dataset.pro]=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;syncProUI();changed()}));$$('[data-camera]').forEach(b=>b.addEventListener('click',()=>{state.pro.view=b.dataset.camera;if(studio)studio.preset(b.dataset.camera)}));$('#spin3d').addEventListener('click',()=>studio?.toggleSpin());$('#fit3d').addEventListener('click',()=>studio?.preset('perspective'));$('#exportAngle').addEventListener('click',e=>busy(e.currentTarget,async()=>{if(!studio)throw Error('Activa un navegador con 3D para exportar esta vista.');const c=await studio.capture('perspective',true);stampClientRender(c,'PERSPECTIVA');const blob=await new Promise(r=>c.toBlob(r,'image/png'));if(!blob)throw Error('No se pudo crear el PNG.');download(blob,fileBase()+'-vista-3d.png');toast('Vista 3D exportada.')}));$('#edit2d').addEventListener('click',()=>{tab('art');setWorkspace('split')});try{studio=new StudioRenderer($('#webglCanvas'));studio.preset(state.pro.view);$('#studioError').hidden=true;studio.rebuild();studio.updateTextures();studio.resize()}catch(e){$('#studioError').hidden=false;$('#studioError').textContent=e.message;$('#exportAngle').disabled=true;$('#spin3d').disabled=true;state.pro.workspace='2d'}syncProUI()}
function stampClientRender(c,label){const ctx=c.getContext('2d');ctx.fillStyle='#213248';ctx.textAlign='center';ctx.font='600 30px Arial';ctx.fillText(GARMENTS[state.garment].label.toUpperCase()+' · '+label,1000,2150);ctx.fillStyle='#5d6e80';ctx.font='24px Arial';ctx.fillText('Referencia visual · material y caída aproximados',1000,2200)}
async function proViewCanvas(view){if(studio)return studio.capture(view);const c=document.createElement('canvas');c.width=2000;c.height=2300;await drawGarment(c,view,{background:'#f4f5f7'});return c}
function validatePro(pro){if(pro===undefined)return {...PRO_DEFAULTS};if(!pro||typeof pro!=='object')throw Error('Ajustes 3D inválidos.');const out={};for(const [k,values]of Object.entries({fit:['regular','relaxed','oversize'],lighting:['soft','side','dramatic'],background:['light','dark'],workspace:['3d','2d','split'],view:['front','back','left','right','perspective']}))out[k]=oneOf(pro[k],values,'3D '+k);for(const [k,min,max]of[['length',80,120],['sleeve',80,120],['folds',0,100],['roughness',10,100]])out[k]=numeric(pro[k],min,max,'3D '+k);out.mannequin=boolean(pro.mannequin,'maniquí');return out}
