/* Local artwork preparation and complete internal reference sheets. No network calls. */
const TECHNIQUES={print:'Serigrafía',sublimation:'Sublimado',embroidery:'Bordado'};
const REF_STATUS={draft:'Borrador',quote:'Por cotizar',sample:'Muestra en desarrollo',review:'Muestra por revisar'};
const COMPOSITIONS={unknown:'Por confirmar',polyester:'100% poliéster',cotton:'100% algodón',polycotton:'Polialgodón',other:'Otra composición'};
const MEASUREMENTS={chest:'Ancho de pecho',length:'Largo total',shoulder:'Ancho de hombros',sleeve:'Largo de manga'};
const REF_TEXT={request:3000,style:100,revision:40,pattern:180,fit:700,construction:1800,tolerance:700,due:10,owner:100,sampleNotes:2400,compositionNotes:500,fabricRef:180,colorRef:180};
const LOGO_TEXT={machineFormat:100,threadSequence:2400,stitchDetails:1200,mesh:300,screenSequence:1800,cure:1000,layoutRef:180,bleed:300,layoutNotes:1400,name:100,colorRefs:500,inkType:180,thread:180,machineRef:180,transfer:500,notes:1200};
const PREP_DEFAULT={removeBg:false,innerWhite:false,cropX:0,cropY:0,cropW:100,cropH:100,tolerance:24,trim:true,mono:false,monoColor:'#18283c'};
const prepDrafts=new Map();
let logoSyncTicket=0,referenceDbPromise=null,referenceSaveQueue=Promise.resolve();
function referenceDefaults(){return {...Object.fromEntries(Object.keys(REF_TEXT).map(k=>[k,''])),status:'draft',composition:'unknown',polyesterPercent:'',sampleSize:'',sampleQty:'',attachments:[],measurements:Object.fromEntries(Object.keys(MEASUREMENTS).map(k=>[k,Object.fromEntries(SIZES.map(s=>[s,'']))]))}}
function logoDefaults(){return {...Object.fromEntries(Object.keys(LOGO_TEXT).map(k=>[k,''])),machineWidth:'',machineHeight:'',colorChanges:'',stops:'',trims:'',threadTotal:'',bobbinTotal:'',screens:'',coverage:'zone',mirror:'pending',widthCm:'',heightCm:'',colorCount:'',stitches:'',underbase:'pending',digitizing:'pending',original:null,prep:{...PREP_DEFAULT},prepared:false}}
function ensureReference(order=state){if(!order.reference)order.reference=referenceDefaults();return order.reference}
function ensureLogo(a){if(!a.logo)a.logo=logoDefaults();return a.logo}
function optionalNumber(value,min,max,label,integer=false){if(value===''||value==null)return '';const n=numeric(value,min,max,label);if(integer&&!Number.isInteger(n))throw Error(label+': usa un número entero.');return n}
function validOptionalDate(value,label){if(value&&(!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(value))||new Date(value).toISOString().slice(0,10)!==value))throw Error(label+' inválida.');return value}
function validateReference(raw){const out=referenceDefaults();if(raw==null)return out;if(typeof raw!=='object'||Array.isArray(raw))throw Error('Ficha inválida.');for(const [key,max]of Object.entries(REF_TEXT))out[key]=safeString(raw[key]??'',max,key);validOptionalDate(out.due,'Fecha de muestra');out.status=oneOf(raw.status??'draft',Object.keys(REF_STATUS),'estado de ficha');out.composition=oneOf(raw.composition??'unknown',Object.keys(COMPOSITIONS),'composición');out.polyesterPercent=optionalNumber(raw.polyesterPercent,0,100,'porcentaje de poliéster');out.sampleSize=oneOf(raw.sampleSize??'',['',...SIZES],'talla de muestra');out.sampleQty=optionalNumber(raw.sampleQty,1,9999,'cantidad de muestras',true);for(const key of Object.keys(MEASUREMENTS))for(const size of SIZES)out.measurements[key][size]=optionalNumber(raw.measurements?.[key]?.[size],0.1,300,'medida '+size);return out}
async function validateLogo(raw,a){const out=logoDefaults();if(raw==null){out.name=a.fileName||'';return out}if(typeof raw!=='object'||Array.isArray(raw))throw Error('Datos del logo inválidos.');for(const [key,max]of Object.entries(LOGO_TEXT))out[key]=safeString(raw[key]??'',max,key);for(const key of ['widthCm','heightCm'])out[key]=optionalNumber(raw[key],0.1,150,key);out.colorCount=optionalNumber(raw.colorCount,1,50,'cantidad de colores',true);out.stitches=optionalNumber(raw.stitches,1,10000000,'puntadas',true);out.underbase=oneOf(raw.underbase??'pending',['pending','yes','no'],'base blanca');out.digitizing=oneOf(raw.digitizing??'pending',['pending','requested','received','sampled'],'ponchado');out.prepared=boolean(raw.prepared??false,'logo preparado');const p=raw.prep??PREP_DEFAULT;out.prep={removeBg:boolean(p.removeBg,'fondo'),innerWhite:boolean(p.innerWhite??false,'blancos interiores'),cropX:numeric(p.cropX??0,0,99,'recorte X'),cropY:numeric(p.cropY??0,0,99,'recorte Y'),cropW:numeric(p.cropW??100,1,100,'recorte ancho'),cropH:numeric(p.cropH??100,1,100,'recorte alto'),tolerance:numeric(p.tolerance,0,100,'tolerancia'),trim:boolean(p.trim,'recorte'),mono:boolean(p.mono,'color único'),monoColor:safeString(p.monoColor,7,'color único')};if(!validHex(out.prep.monoColor))throw Error('Color único inválido.');if(raw.original!=null){const o=raw.original;if(typeof o!=='object')throw Error('Original inválido.');const data=safeString(o.data,7100000,'archivo original'),name=safeString(o.name,150,'archivo original'),type=oneOf(o.type,['png','svg','jpeg'],'tipo de original');await normalizeLogo(data,type);out.original={data,name,type};}return out}

const blankV3=blank;
blank=function(){return {...blankV3(),reference:referenceDefaults()}};
ensureReference();
const validateOrderV3=validateOrder;
validateOrder=async function(raw){const out=await validateOrderV3(raw);out.reference=validateReference(raw.reference);for(let i=0;i<out.artworks.length;i++)out.artworks[i].logo=await validateLogo(raw.artworks[i].logo,out.artworks[i]);return out};

function compositionLabel(){const r=ensureReference();return COMPOSITIONS[r.composition]+(r.composition==='polycotton'&&r.polyesterPercent!==''?' · '+r.polyesterPercent+'% poliéster':'')+(r.compositionNotes?' · '+r.compositionNotes:'')}
function techniqueNotes(a){const r=ensureReference(),l=ensureLogo(a),notes=[];if(a.method==='sublimation'){notes.push('Sublimado por transferencia: apariencia integrada a la tela.');if(r.composition!=='polyester')notes.push('Pendiente: este flujo requiere confirmar 100% poliéster, según la regla del taller.');const rgb=parseColor(state.bodyColor);if(Math.min(...rgb)<205)notes.push('Sobre colores oscuros o intensos el logo pierde contraste. El blanco del archivo deja ver la tela; confirmar en muestra.');}else if(a.method==='embroidery'){notes.push('Bordado: relieve e hilo aproximados. Requiere ponchado y prueba física; la app no genera DST/EMB ni calcula puntadas.');if(l.digitizing==='pending')notes.push('Pendiente de ponchar y definir hilo, estabilizador y detalles pequeños.');}else{notes.push('Serigrafía: capa de tinta aproximada. Definir tintas, colores, base y curado con el taller.');if(['polyester','polycotton'].includes(r.composition))notes.push('En poliéster o mezclas: probar migración de color y compatibilidad de la tinta.');}return notes}
function techniqueBlockers(){return state.artworks.some(a=>a.method==='sublimation'&&(a.kind==='text'?a.text.trim():a.image))&&ensureReference().composition!=='polyester'?['Confirma 100% poliéster en Prenda para exportar un acabado sublimado con la regla de este taller.']:[]}
const photoIssuesV3=photoIssues;
photoIssues=function(views=['front','back']){return [...photoIssuesV3(views),...techniqueBlockers()]};
const signatureV3=visualSignature;
visualSignature=function(){const base=signatureV3(),r=ensureReference();const extra=[r.composition,r.polyesterPercent,r.compositionNotes,r.fabricRef,r.colorRef,state.artworks.map(a=>{const l=ensureLogo(a);return [l.widthCm,l.heightCm,l.colorRefs,l.underbase,l.inkType,l.thread]})];const hasExtra=r.composition!=='unknown'||r.polyesterPercent!==''||r.compositionNotes||r.fabricRef||r.colorRef||extra[5].some(row=>row.some((v,i)=>i===3?v!=='pending':v!==''));if(!hasExtra)return base;const value=base+JSON.stringify(extra);let a=2166136261,b=5381;for(let i=0;i<value.length;i++){a=Math.imul(a^value.charCodeAt(i),16777619);b=Math.imul(b,33)^value.charCodeAt(i)}return(a>>>0).toString(16).padStart(8,'0')+(b>>>0).toString(16).padStart(8,'0')};

function fileData(file,type){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve('data:image/'+(type==='svg'?'svg+xml':type)+';base64,'+String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('No se pudo leer el archivo.'));reader.readAsDataURL(file)})}
async function normalizeLogo(data,type){if(type==='png'||type==='svg')return rasterize(data,type);if(type!=='jpeg'||!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(data))throw Error('Logo inválido.');const header=atob(data.split(',')[1].slice(0,12));if(header.charCodeAt(0)!==255||header.charCodeAt(1)!==216||header.charCodeAt(2)!==255)throw Error('JPG inválido.');const img=await getImage(data);if(img.naturalWidth*img.naturalHeight>25000000)throw Error('Logo demasiado grande; usa hasta 25 megapíxeles.');const c=document.createElement('canvas'),s=Math.min(1,1800/Math.max(img.naturalWidth,img.naturalHeight));c.width=Math.max(1,Math.round(img.naturalWidth*s));c.height=Math.max(1,Math.round(img.naturalHeight*s));c.getContext('2d').drawImage(img,0,0,c.width,c.height);const png=c.toDataURL('image/png');if(png.length>3500000)throw Error('Logo demasiado pesado. Usa una imagen más pequeña.');return png}
async function readLogoFile(file){if(file.size>5*1024*1024)throw Error('El logo excede 5 MB.');const extension=file.name.split('.').pop().toLowerCase(),type={png:'png',svg:'svg',jpg:'jpeg',jpeg:'jpeg'}[extension];if(!type)throw Error('Carga PNG, SVG o JPG.');const data=await fileData(file,type),image=await normalizeLogo(data,type);return{image,original:{data,type,name:file.name.slice(0,150)}}}
async function uploadLogoTo(a,file){const order=state,previous=a.image,payload=await readLogoFile(file);if(state!==order||!state.artworks.includes(a)||a.image!==previous)throw Error('Cambió el pedido o el logo durante la carga. Vuelve a cargarlo.');a.image=payload.image;a.fileName=payload.original.name;a.kind='image';const l=ensureLogo(a);l.original=payload.original;l.prepared=false;l.prep={...PREP_DEFAULT};if(!l.name)l.name=payload.original.name.slice(0,100);prepDrafts.delete(a.id);updateArtList();syncArt();changed();toast('Logo integrado: original, aplicación y ficha guardados juntos.')}
function proofSource(a){return ensureLogo(a).original?.data||a.image}
async function preparedLogoImage(a,options){const l=ensureLogo(a),source=l.original?await normalizeLogo(l.original.data,l.original.type):a.image;if(!source)throw Error('Primero carga un logo.');const img=await getImage(source),c=document.createElement('canvas');options.cropX=clamp(Number(options.cropX)||0,0,99);options.cropY=clamp(Number(options.cropY)||0,0,99);options.cropW=clamp(Number(options.cropW)||100,1,100-options.cropX);options.cropH=clamp(Number(options.cropH)||100,1,100-options.cropY);const sx=Math.floor(img.naturalWidth*options.cropX/100),sy=Math.floor(img.naturalHeight*options.cropY/100);c.width=Math.max(1,Math.floor(img.naturalWidth*options.cropW/100));c.height=Math.max(1,Math.floor(img.naturalHeight*options.cropH/100));const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,sx,sy,c.width,c.height,0,0,c.width,c.height);const pixels=x.getImageData(0,0,c.width,c.height),d=pixels.data,w=c.width,h=c.height;
  if(options.removeBg){const visited=new Uint8Array(w*h),queue=new Uint32Array(w*h);let head=0,tail=0;const threshold=255-options.tolerance;const visit=i=>{if(visited[i])return;visited[i]=1;const n=i*4,min=Math.min(d[n],d[n+1],d[n+2]),max=Math.max(d[n],d[n+1],d[n+2]);if(d[n+3]===0||(min>=threshold&&max-min<=options.tolerance*.8+10))queue[tail++]=i};for(let xx=0;xx<w;xx++){visit(xx);visit((h-1)*w+xx)}for(let yy=0;yy<h;yy++){visit(yy*w);visit(yy*w+w-1)}while(head<tail){const i=queue[head++];d[i*4+3]=0;const xx=i%w,yy=Math.floor(i/w);if(xx>0)visit(i-1);if(xx<w-1)visit(i+1);if(yy>0)visit(i-w);if(yy<h-1)visit(i+w)}}
  if(options.removeBg&&options.innerWhite)for(let n=0;n<d.length;n+=4){const min=Math.min(d[n],d[n+1],d[n+2]),max=Math.max(d[n],d[n+1],d[n+2]);if(min>=255-options.tolerance&&max-min<=options.tolerance*.8+10)d[n+3]=0}
  let minX=w,minY=h,maxX=-1,maxY=-1;const color=parseColor(options.monoColor);for(let i=0;i<w*h;i++){const n=i*4;if(!d[n+3])continue;if(options.mono){d[n]=color[0];d[n+1]=color[1];d[n+2]=color[2]}const xx=i%w,yy=Math.floor(i/w);if(d[n+3]>12){minX=Math.min(minX,xx);maxX=Math.max(maxX,xx);minY=Math.min(minY,yy);maxY=Math.max(maxY,yy)}}if(maxX<0)throw Error('La preparación dejó el logo vacío. Reduce la tolerancia o conserva el fondo.');x.putImageData(pixels,0,0);let result=c;if(options.trim){const crop=document.createElement('canvas');crop.width=maxX-minX+1;crop.height=maxY-minY+1;crop.getContext('2d').drawImage(c,minX,minY,crop.width,crop.height,0,0,crop.width,crop.height);result=crop}const data=result.toDataURL('image/png');if(data.length>3500000)throw Error('El PNG preparado es demasiado pesado.');return data}
function dataBlob(data){const comma=data.indexOf(','),mime=data.slice(5,data.indexOf(';')),bytes=Uint8Array.from(atob(data.slice(comma+1)),c=>c.charCodeAt(0));return new Blob([bytes],{type:mime})}
function logoFileBase(a){return (ensureLogo(a).name||'logo').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').slice(0,70)||'logo'}
function syncReference(){const r=ensureReference();$$('[data-ref]').forEach(el=>{if(document.activeElement!==el)el.value=r[el.dataset.ref]??''});$('#polyesterPercentField').hidden=r.composition!=='polycotton';$$('[data-measure]').forEach(el=>{if(document.activeElement!==el)el.value=r.measurements[el.dataset.measure][el.dataset.size]});}
async function syncLogo(){const ticket=++logoSyncTicket,a=selected();if(!a)return;const l=ensureLogo(a);$$('[data-logo]').forEach(el=>{if(document.activeElement!==el)el.value=l[el.dataset.logo]??''});const draft=prepDrafts.get(a.id)||l.prep;$$('[data-prep]').forEach(el=>{if(document.activeElement===el)return;const value=draft[el.dataset.prep];if(el.type==='checkbox')el.checked=value;else el.value=value});$('#logoToleranceValue').textContent=draft.tolerance;for(const el of $$('[data-tech-fields]'))el.hidden=el.dataset.techFields!==a.method;const advice=$('#techniqueAdvice');advice.replaceChildren();advice.dataset.level=a.method==='sublimation'&&ensureReference().composition!=='polyester'?'review':'info';for(const note of techniqueNotes(a)){const p=document.createElement('p');p.textContent=note;advice.append(p)}$('#addLogo').disabled=state.artworks.length>=12;$('#duplicateLogo').disabled=state.artworks.length>=12;if(a.kind!=='image')l.coverage='zone';$('#logoCoverage').disabled=a.kind!=='image';const fullPiece=a.method==='sublimation'&&l.coverage!=='zone';for(const id of ['artScale','artX','artY','artRotation'])$('#'+id).disabled=fullPiece;for(const id of ['prepareLogo','resetLogo','downloadLogo','downloadOriginal'])$('#'+id).disabled=!a.image;const original=$('#logoOriginalPreview'),prepared=$('#logoPreparedPreview');if(a.image){original.src=proofSource(a);prepared.src=a.image;try{const img=await getImage(a.image);if(ticket!==logoSyncTicket)return;const ppi=l.widthCm?Math.round(img.naturalWidth/(l.widthCm/2.54)):null;const ratio=l.widthCm&&l.heightCm?Math.abs((l.widthCm/l.heightCm)/(img.naturalWidth/img.naturalHeight)-1):0;$('#logoQuality').textContent=img.naturalWidth+' × '+img.naturalHeight+' px aplicados'+(ppi?' · '+ppi+' ppp al ancho solicitado':' · captura el ancho en cm para revisar resolución')+(ppi&&ppi<150?'. Resolución baja: pedir un original de mayor calidad.':'')+(ratio>.08?' Las medidas solicitadas no coinciden con la proporción del logo; confirmar sin deformarlo.':'')+(l.prepared?' · Preparación aplicada.':' · Sin preparación.')}catch{$('#logoQuality').textContent='No se pudo revisar el logo.'}}else{original.removeAttribute('src');prepared.removeAttribute('src');$('#logoQuality').textContent='Carga el archivo original del cliente.'}}
const syncArtV3=syncArt;syncArt=function(){syncArtV3();void syncLogo()};
const updateArtListV3=updateArtList;updateArtList=function(){updateArtListV3();const buttons=$$('#artList .art-item');state.artworks.forEach((a,i)=>{const l=ensureLogo(a),b=buttons[i];if(b){b.querySelector('span').textContent=l.name||(a.kind==='text'?a.text:a.fileName)||'Diseño sin contenido';b.querySelector('small').textContent=(a.view==='front'?'Frente':'Espalda')+' · '+TECHNIQUES[a.method]}});if($('#addLogo'))$('#addLogo').disabled=state.artworks.length>=12};
const populateV3=populate;populate=function(){ensureReference();populateV3();syncReference();void syncLogo()};
const changedV3=changed;changed=function(){changedV3();syncReference();void syncLogo()};

/* IndexedDB keeps complete orders, including original and prepared logos, offline. */
function referenceDb(){if(referenceDbPromise)return referenceDbPromise;referenceDbPromise=new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(Error('Almacenamiento amplio no disponible.'));const request=indexedDB.open('tgm-pedidos-local',1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('records'))request.result.createObjectStore('records',{keyPath:'key'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||Error('No se pudo abrir el almacenamiento.'));request.onblocked=()=>reject(Error('Cierra otra pestaña de este estudio y vuelve a guardar.'))});return referenceDbPromise}
async function dbGet(key){const db=await referenceDb();return new Promise((resolve,reject)=>{const req=db.transaction('records','readonly').objectStore('records').get(key);req.onsuccess=()=>resolve(req.result?.data);req.onerror=()=>reject(req.error)})}
async function dbAll(){const db=await referenceDb();return new Promise((resolve,reject)=>{const req=db.transaction('records','readonly').objectStore('records').getAll();req.onsuccess=()=>resolve(req.result.filter(r=>r.key.startsWith('order:')).map(r=>r.data));req.onerror=()=>reject(req.error)})}
async function dbPut(records){const db=await referenceDb();return new Promise((resolve,reject)=>{const tx=db.transaction('records','readwrite');for(const item of records)tx.objectStore('records').put(item);tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error||Error('No se completó el guardado.'));tx.onerror=()=>reject(tx.error||Error('No se pudo guardar.'))})}
function queueSave(work){const operation=referenceSaveQueue.catch(()=>{}).then(work);referenceSaveQueue=operation;return operation}
function legacyDraft(){for(const key of [KEY,'tgm-estudio-v3','tgm-estudio-v2','tgm-estudio-v1']){try{const raw=localStorage.getItem(key+'.draft');if(raw)return JSON.parse(raw)}catch{}}return null}
async function storedDraft(){let saved=null;try{saved=await dbGet('draft')}catch{}const fallback=legacyDraft();if(saved&&fallback&&fallback.updatedAt>saved.updatedAt)return fallback;return saved||fallback}
const readLibraryV3=()=>readLibrary();
async function allSavedOrders(){let items=[];try{items=await dbAll()}catch{}let older=[];try{older=readLibraryV3()}catch{}const merged=new Map();for(const item of [...older,...items]){const old=merged.get(item.id);if(!old||(item.updatedAt||'')>=(old.updatedAt||''))merged.set(item.id,item)}return [...merged.values()].sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''))}
function saveFeedback(snapshot,ok){if(snapshot.id!==state.id||snapshot.updatedAt!==state.updatedAt)return;storageOk=ok;if(ok){dirty=false;$('#saveStatus').textContent='Pedido, ficha y logos guardados en este dispositivo';$('#saveStatus').dataset.error='false'}else{$('#saveStatus').textContent='Guardado pendiente: descarga el respaldo JSON';$('#saveStatus').dataset.error='true'}}
saveDraft=function(){const snapshot=clone(state);return queueSave(async()=>{try{await dbPut([{key:'draft',data:snapshot}]);saveFeedback(snapshot,true);return true}catch{try{localStorage.setItem(KEY+'.draft',JSON.stringify(snapshot));saveFeedback(snapshot,true);return true}catch{saveFeedback(snapshot,false);return false}}})};
saveOrder=async function(silent=false){clearTimeout(saveTimer);const snapshot=clone(state);return queueSave(async()=>{try{await dbPut([{key:'draft',data:snapshot},{key:'order:'+snapshot.id,data:snapshot}]);saveFeedback(snapshot,true);if(!silent)toast('Pedido completo guardado: ficha, originales y logos aplicados.');return true}catch{try{const list=readLibraryV3(),i=list.findIndex(o=>o.id===snapshot.id);if(i<0)list.unshift(snapshot);else list[i]=snapshot;localStorage.setItem(KEY+'.orders',JSON.stringify(list));localStorage.setItem(KEY+'.draft',JSON.stringify(snapshot));saveFeedback(snapshot,true);if(!silent)toast('Pedido completo guardado en este navegador.');return true}catch{saveFeedback(snapshot,false);toast('No hay espacio disponible. Descarga el respaldo completo JSON.');return false}}})};
openOrders=async function(){const root=$('#savedOrders');root.replaceChildren();const loading=document.createElement('p');loading.textContent='Leyendo pedidos de este dispositivo…';root.append(loading);$('#ordersDialog').showModal();try{const list=await allSavedOrders();root.replaceChildren();if(!list.length){const p=document.createElement('p');p.className='empty';p.textContent='Todavía no hay pedidos guardados.';root.append(p)}for(const order of list){const row=document.createElement('div');row.className='saved-row';const info=document.createElement('div'),title=document.createElement('strong'),meta=document.createElement('small'),button=document.createElement('button');title.textContent=(order.number?'#'+order.number:'Sin folio')+' · '+(order.client||'Sin cliente');meta.textContent=(GARMENTS[order.garment]?.label||'Prenda')+' · '+(order.date||'Sin fecha')+' · '+(order.artworks?.length||0)+' aplicaciones · '+(REF_STATUS[order.reference?.status]||'Borrador');button.textContent='Abrir';button.addEventListener('click',()=>busy(button,()=>loadOrder(order)));info.append(title,meta);row.append(info,button);root.append(row)}}catch{root.textContent='No se pudieron leer los pedidos. Puedes importar un respaldo JSON.'}};
downloadJSON=function(){const text=JSON.stringify(state,null,2);if(new Blob([text]).size>240*1024*1024)return toast('El respaldo excede 240 MB. Reduce el tamaño de los originales antes de descargarlo.');download(new Blob([text],{type:'application/json'}),fileBase()+'-pedido-completo.json');toast('Respaldo completo descargado: ficha, originales, logos y datos internos.')};

function bindV4(){for(const [key,label]of Object.entries(MEASUREMENTS)){const row=document.createElement('tr'),th=document.createElement('th');th.scope='row';th.textContent=label;row.append(th);for(const size of SIZES){const td=document.createElement('td'),input=document.createElement('input');input.type='number';input.min='0.1';input.max='300';input.step='0.1';input.placeholder='—';input.dataset.measure=key;input.dataset.size=size;input.setAttribute('aria-label',label+' talla '+size+' en cm');input.addEventListener('input',()=>{ensureReference().measurements[key][size]=input.value===''?'':clamp(Number(input.value)||0,.1,300);changed()});td.append(input);row.append(td)}$('#measurementRows').append(row)}
  for(const el of $$('[data-ref]'))el.addEventListener(el.tagName==='SELECT'?'change':'input',()=>{let v=el.type==='number'?(el.value===''?'':clamp(Number(el.value)||0,Number(el.min),Number(el.max))):el.value;if(el.type==='number'&&el.step==='1'&&v!=='')v=Math.floor(v);if(el.type==='number'&&el.value!==''&&Number(el.value)!==v)el.value=v;ensureReference()[el.dataset.ref]=v;changed()});
  for(const el of $$('[data-logo]'))el.addEventListener(el.tagName==='SELECT'?'change':'input',()=>{const a=selected();if(!a)return;let v=el.type==='number'?(el.value===''?'':clamp(Number(el.value)||0,Number(el.min),Number(el.max))):el.value;if(el.type==='number'&&el.step==='1'&&v!=='')v=Math.floor(v);if(el.type==='number'&&el.value!==''&&Number(el.value)!==v)el.value=v;ensureLogo(a)[el.dataset.logo]=v;if(el.dataset.logo==='name')updateArtList();changed()});
  for(const el of $$('[data-prep]'))el.addEventListener(el.type==='range'?'input':'change',()=>{const a=selected();if(!a)return;const d={...(prepDrafts.get(a.id)||ensureLogo(a).prep)};d[el.dataset.prep]=el.type==='checkbox'?el.checked:['range','number'].includes(el.type)?Number(el.value):el.value;prepDrafts.set(a.id,d);$('#logoToleranceValue').textContent=d.tolerance});
  $('#artMethod').addEventListener('change',()=>{void syncLogo()});
  $('#addLogo').addEventListener('click',()=>$('#newLogoUpload').click());$('#newLogoUpload').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file||state.artworks.length>=12)return;const order=state;try{const payload=await readLogoFile(file);if(state!==order||state.artworks.length>=12)throw Error('Cambió el pedido durante la carga.');const p=zonePosition('chest','front'),a={id:uid(),view:'front',zone:'chest',kind:'image',text:'',font:'sans',color:'#ffffff',method:'print',...p,rotation:0,image:payload.image,fileName:payload.original.name,dimensions:'',logo:{...logoDefaults(),name:payload.original.name.slice(0,100),original:payload.original}};state.artworks.push(a);selectedArt=a.id;state.photo.side='front';updateArtList();syncArt();changed();toast('Logo cargado. Elige técnica, zona y medidas.')}catch(error){toast(error.message)}});
  $('#prepareLogo').addEventListener('click',e=>busy(e.currentTarget,async()=>{const a=selected();if(!a)return;const order=state,original=proofSource(a),before=a.image,options={...(prepDrafts.get(a.id)||ensureLogo(a).prep)},image=await preparedLogoImage(a,options);if(state!==order||!state.artworks.includes(a)||proofSource(a)!==original||a.image!==before)throw Error('El logo cambió durante la preparación. Vuelve a intentarlo.');const l=ensureLogo(a);if(!l.original)l.original={data:before,name:a.fileName||'original.png',type:'png'};a.image=image;l.prep=options;l.prepared=true;prepDrafts.delete(a.id);syncArt();changed();toast('Logo preparado y aplicado. El original se conserva.')}));
  $('#resetLogo').addEventListener('click',e=>busy(e.currentTarget,async()=>{const a=selected();if(!a||!ensureLogo(a).original)return;const order=state,original=ensureLogo(a).original;const image=await normalizeLogo(original.data,original.type);if(state!==order||!state.artworks.includes(a)||ensureLogo(a).original!==original)throw Error('El pedido cambió; vuelve a intentarlo.');a.image=image;ensureLogo(a).prepared=false;ensureLogo(a).prep={...PREP_DEFAULT};prepDrafts.delete(a.id);syncArt();changed()}));
  $('#downloadLogo').addEventListener('click',()=>{const a=selected();if(a?.image)download(dataBlob(a.image),logoFileBase(a)+'-preparado.png')});$('#downloadOriginal').addEventListener('click',()=>{const a=selected();if(!a)return;const original=ensureLogo(a).original;const data=original?.data||a.image;if(data)download(dataBlob(data),original?.name||logoFileBase(a)+'-original.png')});
  $('#duplicateLogo').addEventListener('click',()=>{const a=selected();if(!a||state.artworks.length>=12)return;const copy=clone(a);copy.id=uid();copy.logo.name=(ensureLogo(a).name||'Aplicación')+' (copia)';copy.logo.name=copy.logo.name.slice(0,100);state.artworks.push(copy);selectedArt=copy.id;updateArtList();syncArt();changed()});
  for(const id of ['openFicha'])$('#'+id).addEventListener('click',e=>busy(e.currentTarget,()=>showReference()));for(const id of ['exportFicha','fichaPdf'])$('#'+id).addEventListener('click',e=>busy(e.currentTarget,()=>exportReference()));for(const id of ['saveFullOrder','fichaSave'])$('#'+id).addEventListener('click',e=>busy(e.currentTarget,()=>saveOrder()));for(const id of ['backupFullOrder','fichaJson'])$('#'+id).addEventListener('click',downloadJSON);
}
const initUIV3=initUI;initUI=function(){initUIV3();bindV4()};
