const COVERAGE={zone:'Logo localizado',body:'Panel de cuerpo completo',leftSleeve:'Manga izquierda',rightSleeve:'Manga derecha',neck:'Cuello / capucha'};
const ATTACHMENT_KINDS={embroidery:'Bordado',sublimation:'Sublimado',print:'Serigrafía',general:'Referencia general'};
const WORKSHOP_NUMBERS={machineWidth:[.1,1500],machineHeight:[.1,1500],colorChanges:[0,9999,true],stops:[0,9999,true],trims:[0,9999,true],threadTotal:[0,99999],bobbinTotal:[0,99999],screens:[1,100,true]};
const validateLogoBasic=validateLogo;
validateLogo=async function(raw,a){const out=await validateLogoBasic(raw,a);for(const [key,[min,max,integer]]of Object.entries(WORKSHOP_NUMBERS))out[key]=optionalNumber(raw?.[key],min,max,key,integer);out.coverage=oneOf(raw?.coverage??'zone',Object.keys(COVERAGE),'pieza');out.mirror=oneOf(raw?.mirror??'pending',['pending','yes','no'],'espejo');return out};
function pieceBox(a){const r=photoRect(state.garment,a.view),l=ensureLogo(a),hood=state.garment==='hoodie';if(l.coverage==='body')return {x:r.x+r.w*.18,y:r.y,w:r.w*.64,h:r.h};if(l.coverage==='neck')return{x:r.x+r.w*.24,y:r.y,w:r.w*.53,h:r.h*(hood?.30:.16)};const right=(l.coverage==='leftSleeve')===(a.view==='front');return{x:r.x+r.w*(right?.70:0),y:r.y+r.h*.06,w:r.w*.30,h:r.h*(hood?.94:.40)}}
function fullSublimation(a){return a.kind==='image'&&a.method==='sublimation'&&ensureLogo(a).coverage!=='zone'}
const photoPoseBasic=photoPose;
photoPose=function(a){if(!fullSublimation(a))return photoPoseBasic(a);const r=pieceBox(a);return{...a,x:r.x+r.w/2,y:r.y+r.h/2,width:r.w,forcedHeight:r.h,rotation:0}};
const artGeometryBasic=artGeometry;
artGeometry=async function(a){return a.forcedHeight?{width:a.width,height:a.forcedHeight}:artGeometryBasic(a)};
function applicationMask(a,rect,wx,wy,src){if(!fullSublimation(a))return 1;const l=ensureLogo(a),u=(wx-rect.x)/rect.w,v=(wy-rect.y)/rect.h;if(u<0||v<0||u>1||v>1)return 0;const ix=clamp(Math.round(u*(src.w-1)),0,src.w-1),iy=clamp(Math.round(v*(src.h-1)),0,src.h-1),neck=src.masks.neck[(iy*src.w+ix)*4+3]/255;if(l.coverage==='neck')return neck;let bodyEdge=.28;if(state.garment==='hoodie')bodyEdge=.28-.065*clamp((v-.14)/.22,0,1);else bodyEdge=.29-.09*clamp((v-.18)/.25,0,1);const body=u>=bodyEdge&&u<=1-bodyEdge;if(l.coverage==='body')return body?1-neck:0;const right=(l.coverage==='leftSleeve')===(a.view==='front');return !body&&(right?u>.5:u<.5)?1-neck:0}
const signatureBasic=visualSignature;
visualSignature=function(){const base=signatureBasic(),parts=state.artworks.filter(fullSublimation).map(a=>[a.id,ensureLogo(a).coverage]);if(!parts.length)return base;let a=2166136261,b=5381;const value=base+JSON.stringify(parts);for(let i=0;i<value.length;i++){a=Math.imul(a^value.charCodeAt(i),16777619);b=Math.imul(b,33)^value.charCodeAt(i)}return(a>>>0).toString(16).padStart(8,'0')+(b>>>0).toString(16).padStart(8,'0')};
async function readReferenceFile(file,kind,note){if(file.size>5*1024*1024)throw Error('La referencia excede 5 MB.');const extension=file.name.split('.').pop().toLowerCase(),mime={pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',dst:'application/octet-stream',emb:'application/octet-stream'}[extension];if(!mime)throw Error('Adjunta PDF, PNG, JPG, DST o EMB.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve('data:'+mime+';base64,'+String(r.result).split(',')[1]);r.onerror=()=>reject(Error('No se pudo leer la referencia.'));r.readAsDataURL(file)});return validateAttachment({id:uid(),name:file.name.slice(0,150),extension,data,kind,note})}
async function validateAttachment(raw){if(!raw||typeof raw!=='object')throw Error('Referencia inválida.');const out={id:safeString(raw.id,100,'id de referencia'),name:safeString(raw.name,150,'nombre de referencia'),extension:oneOf(raw.extension,['pdf','png','jpg','jpeg','dst','emb'],'archivo de referencia'),kind:oneOf(raw.kind,Object.keys(ATTACHMENT_KINDS),'tipo de referencia'),note:safeString(raw.note??'',400,'nota de referencia'),data:safeString(raw.data,7100000,'referencia')};const mime={pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',dst:'application/octet-stream',emb:'application/octet-stream'}[out.extension];if(!out.data.startsWith('data:'+mime+';base64,')||!/^[A-Za-z0-9+/=]+$/.test(out.data.split(',')[1]))throw Error('Referencia dañada.');if(out.extension==='pdf'&&atob(out.data.split(',')[1].slice(0,12)).slice(0,5)!=='%PDF-')throw Error('PDF inválido.');if(['png','jpg','jpeg'].includes(out.extension))await normalizeLogo(out.data,out.extension==='png'?'png':'jpeg');return out}
const validateOrderBasic=validateOrder;
validateOrder=async function(raw){const out=await validateOrderBasic(raw),files=raw.reference?.attachments??[];if(!Array.isArray(files)||files.length>8)throw Error('Máximo 8 referencias por pedido.');const ids=new Set();out.reference.attachments=[];for(const file of files){const item=await validateAttachment(file);if(ids.has(item.id))throw Error('Referencias duplicadas.');ids.add(item.id);out.reference.attachments.push(item)}return out};
function syncReferenceFiles(){const root=$('#referenceFiles');root.replaceChildren();const files=ensureReference().attachments??[];$('#referenceFile').disabled=files.length>=8;if(!files.length){const p=document.createElement('p');p.className='help';p.textContent='Sin referencias adjuntas.';root.append(p)}for(const file of files){const card=document.createElement('div');card.className='reference-file';const title=document.createElement('strong'),meta=document.createElement('p'),actions=document.createElement('div'),get=document.createElement('button'),remove=document.createElement('button');title.textContent=file.name;meta.textContent=ATTACHMENT_KINDS[file.kind]+(file.note?' · '+file.note:'');actions.className='logo-actions';get.textContent='Descargar original';get.addEventListener('click',()=>download(dataBlob(file.data),file.name));remove.textContent='Quitar de este pedido';remove.className='danger';remove.addEventListener('click',()=>{ensureReference().attachments=files.filter(v=>v.id!==file.id);changed();syncReferenceFiles()});card.append(title,meta);if(['png','jpg','jpeg'].includes(file.extension)){const img=document.createElement('img');img.src=file.data;img.alt='Referencia: '+file.name;card.append(img)}actions.append(get,remove);card.append(actions);root.append(card)}}
const populateWorkshopBasic=populate;populate=function(){populateWorkshopBasic();syncReferenceFiles()};
const bindBasic=bindV4;
bindV4=function(){bindBasic();$('#referenceFile').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;const order=state,kind=$('#referenceFileKind').value,note=$('#referenceFileNote').value;if((ensureReference().attachments??[]).length>=8)return toast('Máximo 8 referencias por pedido.');try{const item=await readReferenceFile(file,kind,note);if(state!==order)throw Error('El pedido cambió durante la carga.');const r=ensureReference();if((r.attachments??[]).length>=8)throw Error('Máximo 8 referencias por pedido.');(r.attachments??=[]).push(item);$('#referenceFileNote').value='';changed();syncReferenceFiles();toast('Referencia adjunta al pedido completo.')}catch(error){toast(error.message)}})};
function workshopRows(a){const l=ensureLogo(a);if(a.method==='embroidery')return[['Formato de máquina',l.machineFormat],['Dimensiones de ponchado',referenceValue(l.machineWidth)+' × '+referenceValue(l.machineHeight)+' mm'],['Cambios / paradas / recortes',[l.colorChanges,l.stops,l.trims].map(referenceValue).join(' / ')],['Hilo / bobina',referenceValue(l.threadTotal)+' m de hilo · '+referenceValue(l.bobbinTotal)+' m de bobina'],['Secuencia del ponchado',l.threadSequence],['Detalles de puntada',l.stitchDetails]];if(a.method==='print')return[['Pantallas / esténciles',l.screens],['Malla y registro',l.mesh],['Secuencia de colores',l.screenSequence],['Rasero, secado y curado',l.cure]];return[['Cobertura / pieza',COVERAGE[l.coverage]],['Lámina de impresión',l.layoutRef],['Espejo de transferencia',{pending:'Por confirmar',yes:'Solicitado en el archivo de impresión',no:'No solicitado'}[l.mirror]],['Sangrado / costura',l.bleed],['Acomodo y transferencia',l.layoutNotes],['Recorte de lámina','X '+l.prep.cropX+'% · Y '+l.prep.cropY+'% · ancho '+l.prep.cropW+'% · alto '+l.prep.cropH+'%']];}
