/* Sleeve-specific controls share the existing artwork, rendering and order pipelines. */
const SLEEVE_NAMES={left:'Manga izquierda',right:'Manga derecha'};
const SLEEVE_DETAILS={none:'Sin detalle adicional',edge:'Borde en contraste',single:'Una franja',double:'Dos franjas'};
const sleeveUI={side:'left',view:'front'};
let pendingSleeveUpload=null;
function sleeveDefaults(){const one=()=>({panel:false,color:'#f4f3ef',detail:'none',bandColor:'#18283c',bandWidth:8,bandCm:'',notes:''});return{left:one(),right:one()}}
function ensureSleeves(order=state){if(!order.sleeves)order.sleeves=sleeveDefaults();return order.sleeves}
function validateSleeves(raw){const out=sleeveDefaults();if(raw==null)return out;if(typeof raw!=='object'||Array.isArray(raw))throw Error('Detalles de mangas inválidos.');for(const side of ['left','right']){const s=raw[side];if(s==null)continue;if(typeof s!=='object'||Array.isArray(s))throw Error('Manga inválida.');const d=out[side];d.panel=boolean(s.panel??false,'color de manga');for(const k of ['color','bandColor']){d[k]=safeString(s[k]??d[k],7,k);if(!validHex(d[k]))throw Error('Color de manga inválido.')}d.detail=oneOf(s.detail??'none',Object.keys(SLEEVE_DETAILS),'detalle de manga');d.bandWidth=numeric(s.bandWidth??8,3,20,'grosor de franja');d.bandCm=optionalNumber(s.bandCm,.1,30,'ancho de detalle');d.notes=safeString(s.notes??'',1200,'notas de manga')}return out}
const blankBeforeSleeves=blank;
blank=function(){return{...blankBeforeSleeves(),sleeves:sleeveDefaults()}};
ensureSleeves();
const validateBeforeSleeves=validateOrder;
validateOrder=async function(raw){const out=await validateBeforeSleeves(raw);out.sleeves=validateSleeves(raw.sleeves);return out};
function sleeveZoneName(side){return side==='left'?'leftSleeve':'rightSleeve'}
function sleeveSideForZone(zone){return zone==='leftSleeve'?'left':zone==='rightSleeve'?'right':null}
function sleeveVisualState(){const s=ensureSleeves();return ['left','right'].map(side=>{const d=s[side];return[d.panel?d.color:null,d.detail,d.detail!=='none'?d.bandColor:null,d.detail!=='none'?d.bandWidth:null]})}
function hasSleeveDetails(){return Object.values(ensureSleeves()).some(s=>s.panel||s.detail!=='none')}
const signatureBeforeSleeves=visualSignature;
visualSignature=function(){const base=signatureBeforeSleeves();if(!hasSleeveDetails()&&!state.artworks.some(a=>sleeveSideForZone(a.zone)||['leftSleeve','rightSleeve'].includes(ensureLogo(a).coverage)))return base;const value=base+'sleeves-v5'+JSON.stringify(sleeveVisualState());let a=2166136261,b=5381;for(let i=0;i<value.length;i++){a=Math.imul(a^value.charCodeAt(i),16777619);b=Math.imul(b,33)^value.charCodeAt(i)}return(a>>>0).toString(16).padStart(8,'0')+(b>>>0).toString(16).padStart(8,'0')};

/* Approximate sewn-sleeve boundaries on the fixed photo bases, clipped by their alpha. */
const SLEEVE_SEAMS={
 playera:[[.09,.151],[.19,.172],[.28,.197],[.36,.218],[.43,.202]],
 polo:[[.14,.151],[.25,.176],[.35,.205],[.43,.213],[.48,.203]],
 hoodie:[[.21,.145],[.29,.187],[.42,.207],[.55,.226],[.77,.195],[.92,.176],[1,.163]]
};
function sleeveRegion(u,v,garment=state.garment,view='front'){
  if(u<0||v<0||u>1||v>1)return null;
  const points=SLEEVE_SEAMS[garment];if(v<points[0][0]||v>points.at(-1)[0])return null;
  let edge=points.at(-1)[1];for(let i=1;i<points.length;i++)if(v<=points[i][0]){const [v0,u0]=points[i-1],[v1,u1]=points[i];edge=u0+(u1-u0)*(v-v0)/(v1-v0);break}
  const screenRight=u>.5,outer=screenRight?1-u:u;if(outer>edge)return null;
  const side=screenRight===(view==='front')?'left':'right';
  const hem=garment==='hoodie'?.991:garment==='polo'?.414+outer*.31:.36+outer*.32;
  return{side,hem,depth:hem-v};
}
function makeSleevePalette(view){const s=ensureSleeves();return{view,garment:state.garment,cuff:state.contrast.cuff,sides:Object.fromEntries(['left','right'].map(side=>[side,{...s[side],panelColor:s[side].panel?parseColor(s[side].color):null,trimColor:parseColor(s[side].bandColor)}]))}}
function sleeveColorAt(u,v,palette,cuffAlpha){const r=sleeveRegion(u,v,palette.garment,palette.view);if(!r)return null;const s=palette.sides[r.side],w=(palette.garment==='hoodie'?.77:.4)*s.bandWidth/100;let band=false;if(s.detail==='edge')band=r.depth>=-.015&&r.depth<=w;else if(s.detail==='single')band=r.depth>=w*.8&&r.depth<=w*1.8;else if(s.detail==='double')band=(r.depth>=w*.4&&r.depth<=w*1.4)||(r.depth>=w*2&&r.depth<=w*3);if(band)return s.trimColor;if(palette.cuff&&cuffAlpha>128)return null;return s.panelColor}
const maskBeforeSleeves=applicationMask;
applicationMask=function(a,rect,wx,wy,src){let side=sleeveSideForZone(a.zone);if(fullSublimation(a)){const coverage=ensureLogo(a).coverage;if(!['leftSleeve','rightSleeve'].includes(coverage))return maskBeforeSleeves(a,rect,wx,wy,src);side=sleeveSideForZone(coverage)}if(!side)return maskBeforeSleeves(a,rect,wx,wy,src);const r=sleeveRegion((wx-rect.x)/rect.w,(wy-rect.y)/rect.h,state.garment,a.view);return r?.side===side?1:0};
const zoneBeforeSleeves=photoZone;
photoZone=function(zone,view){const old=zoneBeforeSleeves(zone,view);if(!sleeveSideForZone(zone))return old;const r=photoRect(state.garment,view),right=(zone==='leftSleeve')===(view==='front');return{...old,x:r.x+r.w*(right?.875:.125),y:r.y+r.h*(state.garment==='hoodie'?.49:state.garment==='polo'?.32:.285)}};

function sleeveDescription(side){const s=ensureSleeves()[side];return(s.panel?'Color propio '+s.color.toUpperCase():'Color del cuerpo')+(s.detail!=='none'?' · '+SLEEVE_DETAILS[s.detail]+' '+s.bandColor.toUpperCase()+(s.bandCm!==''?' · ancho solicitado '+s.bandCm+' cm':''): '')}
function sleeveReferenceRows(){const rows=[];for(const side of ['left','right']){const s=ensureSleeves()[side];rows.push([SLEEVE_NAMES[side]+' · detalle',sleeveDescription(side)+(s.detail!=='none'?' · grosor visual '+s.bandWidth+'% (no calibrado)':'' )]);if(s.notes)rows.push([SLEEVE_NAMES[side]+' · notas',s.notes])}return rows}
const specsBeforeSleeves=clientSpecLines;
clientSpecLines=function(){const lines=specsBeforeSleeves();for(const side of ['left','right']){const s=ensureSleeves()[side];if(s.panel||s.detail!=='none')lines.splice(4,0,[side==='left'?'Manga izq.':'Manga der.',sleeveDescription(side)])}return lines};
const techniqueNotesBeforeSleeves=techniqueNotes;
techniqueNotes=function(a){const notes=techniqueNotesBeforeSleeves(a),side=sleeveSideForZone(a.zone);if(side){notes.push(SLEEVE_NAMES[side]+' al vestir · '+(a.view==='front'?'visible desde el frente':'visible desde la espalda')+'. Confirmar tamaño y distancia a costuras.');const pose=photoPose(a),r=photoRect(state.garment,a.view);if(!fullSublimation(a)&&sleeveRegion((pose.x-r.x)/r.w,(pose.y-r.y)/r.h,state.garment,a.view)?.side!==side)notes.push('El centro del diseño está fuera de la manga. Vuelve a elegir su zona para centrarlo.')}return notes};

function sleeveCrop(side,view){const r=photoRect(state.garment,view),right=(side==='left')===(view==='front'),hood=state.garment==='hoodie';return{x:r.x+r.w*(right?.685:-.025),y:r.y+r.h*(hood?.17:.055),w:r.w*.34,h:r.h*(hood?.85:.46)}}
function drawSleeveCloseup(target,source,side,view,stamp=false){const ctx=target.getContext('2d'),crop=sleeveCrop(side,view);ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#f0f2f7';ctx.fillRect(0,0,target.width,target.height);const bottom=stamp?target.height*.13:0,s=Math.min((target.width-24)/crop.w,(target.height-bottom-24)/crop.h),w=crop.w*s,h=crop.h*s;ctx.drawImage(source,crop.x/W*source.width,crop.y/H*source.height,crop.w/W*source.width,crop.h/H*source.height,(target.width-w)/2,(target.height-bottom-h)/2,w,h);if(stamp){ctx.fillStyle='#253148';ctx.textAlign='center';ctx.font='600 '+Math.round(target.width*.023)+'px Arial';ctx.fillText(SLEEVE_NAMES[side].toUpperCase()+' · '+(view==='front'?'FRENTE':'ESPALDA'),target.width/2,target.height*.93);ctx.font=Math.round(target.width*.015)+'px Arial';ctx.fillStyle='#657089';ctx.fillText('Lado al vestir · apariencia y ubicación aproximadas',target.width/2,target.height*.971)}}
function updateSleevePreview(canvases){const c=$('#sleeveCanvas');if(!c)return;if(ensurePhoto().source==='final'){const x=c.getContext('2d');x.fillStyle='#eef0f5';x.fillRect(0,0,c.width,c.height);x.fillStyle='#4d5d74';x.font='23px Arial';x.textAlign='center';x.fillText('Render final cargado',c.width/2,c.height/2-18);x.font='18px Arial';x.fillText('Revisa las mangas en la imagen completa.',c.width/2,c.height/2+18)}else drawSleeveCloseup(c,canvases[sleeveUI.view==='front'?0:1],sleeveUI.side,sleeveUI.view);$('#sleeveCaption').textContent=SLEEVE_NAMES[sleeveUI.side]+' al vestir · '+(sleeveUI.view==='front'?'frente':'espalda')}
async function exportSleeve(){if(ensurePhoto().source!=='generated')throw Error('El acercamiento de manga usa la base generada. Revisa el render final completo.');const side=sleeveUI.side,view=sleeveUI.view,signature=visualSignature(),source=await exportCanvas(view),c=document.createElement('canvas');c.width=1600;c.height=1300;drawSleeveCloseup(c,source,side,view,true);if(visualSignature()!==signature)throw Error('El pedido cambió; vuelve a exportar.');download(dataBlob(c.toDataURL('image/png')),fileBase()+'-manga-'+(side==='left'?'izquierda':'derecha')+'-'+(view==='front'?'frente':'espalda')+'.png');toast('Acercamiento de manga listo.');return c}
const openDetailBeforeSleeves=openPhotoDetail;
openPhotoDetail=async function(preset){photoDetail.sleeveSide=null;return openDetailBeforeSleeves(preset)};
const refreshDetailBeforeSleeves=refreshPhotoDetail;
refreshPhotoDetail=async function(){if(photoDetail.sleeveSide&&photoDetail.sleeveView!==photoDetail.view){const p=photoZone(sleeveZoneName(photoDetail.sleeveSide),photoDetail.view);Object.assign(photoDetail,{x:p.x,y:p.y,sleeveView:photoDetail.view})}return refreshDetailBeforeSleeves()};
async function zoomSleeve(){if(ensurePhoto().source!=='generated')return openPhotoDetail();const p=photoZone(sleeveZoneName(sleeveUI.side),sleeveUI.view);Object.assign(photoDetail,{view:sleeveUI.view,sleeveView:sleeveUI.view,sleeveSide:sleeveUI.side,zoom:3.4,x:p.x,y:p.y});$('#detailView').value=sleeveUI.view;$('#photoDetailDialog').showModal();await refreshPhotoDetail()}

function showSleeves(side){if(side)sleeveUI.side=side;sleeveUI.view=ensurePhoto().side==='back'?'back':'front';setWorkspace('photo',false);tab('sleeves');syncSleeves();schedulePhoto()}
function newSleeveArt({payload=null,copy=null,text=false,side=sleeveUI.side,view=sleeveUI.view,method=$('#sleeveMethod').value}={}){if(state.artworks.length>=12)throw Error('Máximo 12 aplicaciones por pedido.');const zone=sleeveZoneName(side),p=zonePosition(zone,view),right=(side==='left')===(view==='front');const a={id:uid(),view,zone,kind:text?'text':'image',text:'',font:'sans',color:'#ffffff',method,...p,rotation:state.garment==='hoodie'?0:right?-18:18,image:'',fileName:'',dimensions:'',logo:logoDefaults()};if(payload){a.image=payload.image;a.fileName=payload.original.name;a.logo.original=payload.original;a.logo.name=payload.original.name.slice(0,100)}if(copy){a.kind=copy.kind;a.text=copy.text;a.font=copy.font;a.color=copy.color;a.method=copy.method;a.image=copy.image;a.fileName=copy.fileName;const l=ensureLogo(copy);a.logo.original=l.original?clone(l.original):null;a.logo.prepared=l.prepared;a.logo.prep=clone(l.prep);a.logo.name=(l.name||copy.text||copy.fileName||'Aplicación').slice(0,100);a.logo.colorRefs=l.colorRefs}state.artworks.push(a);selectedArt=a.id;state.photo.side=view;updateArtList();syncArt();changed();return a}
function editSleeveArt(a){selectedArt=a.id;sleeveUI.side=sleeveSideForZone(a.zone)||sleeveUI.side;sleeveUI.view=a.view;state.photo.side=a.view;setWorkspace('photo',false);tab('art');updateArtList();syncArt();schedulePhoto();if(a.kind==='text')$('#artText').focus();toast(SLEEVE_NAMES[sleeveUI.side]+' seleccionada. Ajusta el contenido y sus medidas.');}
function syncSleeves(){const data=ensureSleeves()[sleeveUI.side];$$('[data-sleeve-side]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.sleeveSide===sleeveUI.side));$('#sleeveView').value=sleeveUI.view;for(const el of $$('[data-sleeve-field]'))if(document.activeElement!==el){const value=data[el.dataset.sleeveField];if(el.type==='checkbox')el.checked=value;else el.value=value}$('#sleeveColor').disabled=!data.panel;for(const id of ['sleeveBandColor','sleeveBandWidth','sleeveBandCm'])$('#'+id).disabled=data.detail==='none';$('#sleevePng').disabled=ensurePhoto().source!=='generated';const a=selected(),location=$('#sleeveLogoLocation');location.hidden=!a||!sleeveSideForZone(a.zone);if(!location.hidden)location.textContent=ZONES[a.zone].label+' · '+(a.view==='front'?'frente':'espalda')+' · el logo se recorta al área de la manga';const list=$('#sleeveArtList');list.replaceChildren();const arts=state.artworks.filter(a=>a.zone===sleeveZoneName(sleeveUI.side));if(!arts.length){const p=document.createElement('p');p.className='help';p.textContent='Esta manga aún no tiene logos ni textos.';list.append(p)}for(const a of arts){const b=document.createElement('button'),name=document.createElement('span'),meta=document.createElement('small');b.className='sleeve-art';name.textContent=ensureLogo(a).name||a.text||a.fileName||'Contenido pendiente';meta.textContent=(a.view==='front'?'Frente':'Espalda')+' · '+TECHNIQUES[a.method]+' · Editar';b.append(name,meta);b.addEventListener('click',()=>editSleeveArt(a));list.append(b)}const reuse=$('#sleeveExisting'),previous=reuse.value;reuse.replaceChildren();reuse.add(new Option('Selecciona una aplicación',''));for(const a of state.artworks){const label=ensureLogo(a).name||a.text||a.fileName;if(!label)continue;reuse.add(new Option(label+' · '+ZONES[a.zone].label,a.id))}reuse.value=previous;for(const id of ['sleeveUpload','sleeveText','sleeveReuse'])$('#'+id).disabled=state.artworks.length>=12||(id==='sleeveReuse'&&!state.artworks.length)}
const populateBeforeSleeves=populate;populate=function(){ensureSleeves();populateBeforeSleeves();syncSleeves()};
const changedBeforeSleeves=changed;changed=function(){changedBeforeSleeves();syncSleeves()};
const syncArtBeforeSleeves=syncArt;syncArt=function(){syncArtBeforeSleeves();syncSleeves()};
const tabBeforeSleeves=tab;tab=function(name,focus=false){if(name==='sleeves'){setWorkspace('photo',false);syncSleeves()}tabBeforeSleeves(name,focus)};
function bindSleeves(){for(const id of ['photoSleeves','artSleeves'])$('#'+id).addEventListener('click',()=>showSleeves(sleeveSideForZone(selected()?.zone)));for(const b of $$('[data-sleeve-side]'))b.addEventListener('click',()=>{sleeveUI.side=b.dataset.sleeveSide;syncSleeves();schedulePhoto()});$('#sleeveView').addEventListener('change',e=>{sleeveUI.view=e.target.value;state.photo.side=e.target.value;changed()});for(const el of $$('[data-sleeve-field]'))el.addEventListener(el.tagName==='SELECT'||el.type==='checkbox'?'change':'input',()=>{let value=el.type==='checkbox'?el.checked:el.value;if(el.type==='number')value=value===''&&el.dataset.sleeveField==='bandCm'?'':clamp(Number(value)||Number(el.min),Number(el.min),Number(el.max));if(el.type==='number'&&el.value!==''&&Number(el.value)!==value)el.value=value;ensureSleeves()[sleeveUI.side][el.dataset.sleeveField]=value;changed()});$('#sleeveCopyDetails').addEventListener('click',()=>{const other=sleeveUI.side==='left'?'right':'left';ensureSleeves()[other]=clone(ensureSleeves()[sleeveUI.side]);changed();toast('Detalles copiados a '+SLEEVE_NAMES[other].toLowerCase()+'. Los logos se añaden por separado.')});$('#sleeveUpload').addEventListener('click',()=>{pendingSleeveUpload={order:state,side:sleeveUI.side,view:sleeveUI.view,method:$('#sleeveMethod').value};$('#sleeveLogoFile').click()});$('#sleeveLogoFile').addEventListener('change',async e=>{const file=e.target.files[0],target=pendingSleeveUpload||{order:state,side:sleeveUI.side,view:sleeveUI.view,method:$('#sleeveMethod').value};e.target.value='';pendingSleeveUpload=null;if(!file)return;try{const payload=await readLogoFile(file);if(state!==target.order)throw Error('El pedido cambió durante la carga.');editSleeveArt(newSleeveArt({...target,payload}))}catch(error){toast(error.message)}});$('#sleeveText').addEventListener('click',()=>{try{editSleeveArt(newSleeveArt({text:true}))}catch(error){toast(error.message)}});$('#sleeveReuse').addEventListener('click',()=>{const a=state.artworks.find(a=>a.id===$('#sleeveExisting').value);if(!a)return toast('Selecciona la aplicación que quieres copiar.');try{editSleeveArt(newSleeveArt({copy:a}))}catch(error){toast(error.message)}});$('#sleeveZoom').addEventListener('click',e=>busy(e.currentTarget,zoomSleeve));$('#sleevePng').addEventListener('click',e=>busy(e.currentTarget,exportSleeve));}
const initUIBeforeSleeves=initUI;initUI=function(){initUIBeforeSleeves();bindSleeves();$('#detailFit').addEventListener('click',()=>{photoDetail.sleeveSide=null})};
