"""Assemble the standalone app from the retained v2 app and the photo studio.
Re-running is deterministic. No network/build dependencies required.
"""
from pathlib import Path
import base64, json, re
root = Path(__file__).resolve().parent
html = (root / 'v2-reference.html').read_text()
assets = {kind: 'data:image/png;base64,' + base64.b64encode((root / 'assets' / name).read_bytes()).decode()
          for kind, name in [
              ('playera', 'cotton-tshirt-front-back.png'),
              ('hoodie', 'pullover-hoodie-front-back.png'),
              ('polo', 'pique-polo-front-back.png'),
              ('sleeveless', 'chifon-sleeveless-hombre-front-back.png'),
              ('sleevelessMujer', 'chifon-sleeveless-mujer-front-back.png'),
              ('zipneck', 'chifon-zipneck-front-back.png'),
          ]}
html = html.replace('</style>', (root / 'photo.css').read_text() + '</style>', 1)
html = html.replace('<title>TGM · Estudio 3D de prendas</title>', '<title>TGM · Estudio de acabado de prendas</title>')
html = html.replace('3D · v2', 'ESTUDIO · v3').replace('Funciona sin conexión · v2.0', 'Funciona sin conexión · v3.0')
html = html.replace('Diseña en 3D. Prepara el pedido. Comparte el resultado.', 'Configura la prenda y revisa su acabado antes de compartirla.')
html = html.replace('<h2>Estudio 3D</h2>', '<h2>Vista de acabado</h2>')
html = html.replace('Prenda editable · <span id="proFitLabel">Regular</span>', 'Referencia de prenda · <span id="proFitLabel">Regular</span>')
html = html.replace('<button data-workspace="3d" aria-pressed="true">3D</button>', '<button data-workspace="photo" aria-pressed="true">Acabado</button><button data-workspace="3d" aria-pressed="false">Boceto 3D</button>')
html = html.replace('>3D + 2D</button>', '>3D + 2D</button>')
html = html.replace('<div id="proWorkspace" data-mode="3d">', '<div id="proWorkspace" data-mode="photo">' + (root / 'workspace.html').read_text())
html = html.replace('>Vista 3D</button></nav>', '>Boceto 3D</button><button role="tab" id="tab-photo" data-tab="photo" aria-controls="panel-photo" aria-selected="false" tabindex="-1">Acabado</button></nav>')
html = html.replace('<div id="panel-studio"', (root / 'panel.html').read_text() + '<div id="panel-studio"', 1)
html = html.replace('<dialog id="zoomDialog"', (root / 'detail.html').read_text() + '<dialog id="zoomDialog"', 1)
html = html.replace('Render 3D, sin datos internos.', 'Exporta la vista de acabado, sin datos internos.')
html = html.replace('Propiedades de la vista 3D', 'Propiedades del boceto 3D')
html = html.replace('Estas proporciones ajustan la apariencia del modelo. No son medidas de patrón ni una prueba de ajuste.', 'Estas proporciones modifican el boceto 3D. La base de acabado conserva su propia confección y no calcula medidas de patrón ni ajuste.')
html = html.replace('>Realista</button>', '>Sombreado</button>')
html = html.replace("['#9babb8','Gris']", "['#9babb8','Gris'],['#8051b3','Morado']")
html = html.replace('<span class="badge">Textura aproximada</span>', '<span class="badge">Referencia visual</span>')
html = html.replace('Las medidas visuales son proporcionales. Las partes fuera de la prenda se recortan.', 'Las posiciones y el ancho son proporcionales, no centímetros. Revisa la colocación sobre la imagen de acabado; las partes fuera de la prenda se recortan.')
# Place all photo declarations before state initialization.
html = html.replace('<script>\n', '<script>\nconst PHOTO_ASSETS=' + json.dumps(assets, separators=(',', ':')) + ';\n' + (root / 'photo.js').read_text() + '\n', 1)
html = html.replace("workspace:'3d'", "workspace:'photo'", 1)
html = html.replace("workspace:['3d','2d','split']", "workspace:['photo','3d','2d','split']")
html = html.replace("VERSION=2,KEY='tgm-estudio-v2'", "VERSION=3,KEY='tgm-estudio-v3'")
html = html.replace("schema:SCHEMA,version:VERSION,pro:{...PRO_DEFAULTS},id:uid()", "schema:SCHEMA,version:VERSION,pro:{...PRO_DEFAULTS},photo:{...PHOTO_DEFAULTS,final:{front:null,back:null}},id:uid()")
html = html.replace("||localStorage.getItem('tgm-estudio-v1.", "||localStorage.getItem('tgm-estudio-v2.", 2)
html = html.replace("localStorage.getItem('tgm-estudio-v2.orders');", "localStorage.getItem('tgm-estudio-v2.orders')||localStorage.getItem('tgm-estudio-v1.orders');")
html = html.replace("localStorage.getItem('tgm-estudio-v2.draft');", "localStorage.getItem('tgm-estudio-v2.draft')||localStorage.getItem('tgm-estudio-v1.draft');")
html = html.replace("![1,2].includes(raw.version)", "![1,2,3].includes(raw.version)")
html = html.replace('(versiones 1 y 2).', '(versiones 1, 2 y 3).')
html = html.replace('out.pro=validatePro(raw.pro);return out}', "out.pro=validatePro(raw.pro);out.photo=await validatePhoto(raw.photo);if(raw.version<3)out.pro.workspace='photo';return out}")
html = html.replace('updateSummary();scheduleRender();', 'updateSummary();scheduleRender();schedulePhoto();', 1)
html = html.replace('syncProUI();scheduleRender()}\nfunction tab', 'syncProUI();scheduleRender();schedulePhoto()}\nfunction tab')
html = html.replace("p.hidden=p.id!=='panel-'+name);scheduleRender()", "p.hidden=p.id!=='panel-'+name);scheduleRender();schedulePhoto()")
html = html.replace("state.neck=GARMENTS[state.garment].necks[0][0];configureNeck();populate();changed()", "state.neck=GARMENTS[state.garment].necks[0][0];photoBaseDefaults();configureNeck();populate();changed()")
html = html.replace("b.addEventListener('click',()=>{selectedArt=a.id;updateArtList();syncArt();scheduleRender()})", "b.addEventListener('click',()=>{selectedArt=a.id;if(state.photo.side!=='both')state.photo.side=a.view;updateArtList();syncArt();scheduleRender();schedulePhoto()})")
html = html.replace("a.view=e.target.value;if(a.zone", "a.view=e.target.value;if(state.photo.side!=='both')state.photo.side=a.view;if(a.zone")
html = html.replace("if(studio)await studio.updateTextures();", "if(studio&&state.pro.workspace!=='photo')await studio.updateTextures();")
html = html.replace('populate();initPro();if(hadDraft)', 'populate();initPro();initPhoto();if(hadDraft)')
# The photo studio works without WebGL. A WebGL fallback must not hide it.
html = html.replace("state.pro.workspace='2d'}syncProUI()", "if(state.pro.workspace!=='photo')state.pro.workspace='2d'}syncProUI()")
html = html.replace("function setWorkspace(mode,save=true){state.pro.workspace=mode;", "function setWorkspace(mode,save=true){state.pro.workspace=mode;$('#studioError').hidden=mode==='photo'||!!studio;")
# All client PNG/PDF export paths now use the finished-look compositor.
html = re.sub(r'async function proViewCanvas\(view\)\{.*?\}\nfunction validatePro', "async function proViewCanvas(view){assertPhotoReady([view]);const c=document.createElement('canvas');c.width=2000;c.height=2300;await renderPhoto(c,view,{background:true});return c}\nfunction validatePro", html, count=1, flags=re.S)
html = html.replace("async function exportCanvas(view){const c=await proViewCanvas(view);stampClientRender(c,view==='front'?'FRENTE':'ESPALDA');return c}", "async function exportCanvas(view){const signature=visualSignature(),settings=JSON.stringify(state.photo);const c=await exportPhoto(view);if(visualSignature()!==signature||JSON.stringify(state.photo)!==settings)throw Error('El pedido cambió durante el render; vuelve a exportar.');return c}")
html = html.replace("async function summaryCanvas(){const c=", "async function summaryCanvas(){assertPhotoReady();const summaryRevision=state.updatedAt;const c=")
html = html.replace("antes de producir.',margin+22,2260);return c}", "antes de producir.',margin+22,2260);if(state.updatedAt!==summaryRevision)throw Error('El pedido cambió durante el PDF; vuelve a exportar.');return c}")
html = html.replace("Visualización de referencia. Textura, caída, color y bordado aproximados.',margin+22,2227)", "Referencia visual. Base generada o render cargado; verificar el acabado.',margin+22,2227)")
html = html.replace("y-font*.65", "y-font-7")
# Native Ctrl+P must use the same images, and must show mismatch information.
html = html.replace("await drawGarment($('#printFront'),'front');await drawGarment($('#printBack'),'back');", "await renderPhoto($('#printFront'),'front',{background:true});await renderPhoto($('#printBack'),'back',{background:true});")
html = html.replace("const rows=clientSpecLines();$('#nativePrintTitle')", "const rows=clientSpecLines();const issues=photoIssues();if(issues.length)rows.unshift(['Referencia pendiente',issues.join(' ')]);$('#nativePrintTitle')")
html = html.replace("e.key==='End'?3:", "e.key==='End'?tabs.length-1:")
html = html.replace("40*1024*1024", "60*1024*1024").replace('El JSON excede 40 MB.', 'El JSON excede 60 MB.')
html = html.replace('init();\n</script>', "init().catch(e=>toast('No se pudo iniciar el estudio: '+e.message));\n</script>")
(root.parent / 'dist').mkdir(exist_ok=True)
import importlib.util
v4_spec = importlib.util.spec_from_file_location('tgm_v4_compose', root / 'order-v4' / 'compose.py')
v4 = importlib.util.module_from_spec(v4_spec)
v4_spec.loader.exec_module(v4)
html = v4.extend(html, root)
v5_spec = importlib.util.spec_from_file_location('tgm_sleeves_compose', root / 'sleeves-v5' / 'compose.py')
v5 = importlib.util.module_from_spec(v5_spec)
v5_spec.loader.exec_module(v5)
html = v5.extend(html, root)
v6_spec = importlib.util.spec_from_file_location('tgm_reliability_compose', root / 'reliability-v6' / 'compose.py')
v6 = importlib.util.module_from_spec(v6_spec)
v6_spec.loader.exec_module(v6)
html = v6.extend(html, root)
cloud_spec = importlib.util.spec_from_file_location('tgm_cloud_compose', root / 'cloud' / 'compose.py')
cloud = importlib.util.module_from_spec(cloud_spec)
cloud_spec.loader.exec_module(cloud)
html = cloud.extend(html, root)
pricing_spec = importlib.util.spec_from_file_location('tgm_pricing_compose', root / 'pricing-v7' / 'compose.py')
pricing = importlib.util.module_from_spec(pricing_spec)
pricing_spec.loader.exec_module(pricing)
html = pricing.extend(html, root)
project_spec = importlib.util.spec_from_file_location('tgm_project_v8_compose', root / 'project-v8' / 'compose.py')
project = importlib.util.module_from_spec(project_spec)
project_spec.loader.exec_module(project)
html = project.extend(html, root)
garments_spec = importlib.util.spec_from_file_location('tgm_garments_v82_compose', root / 'garments-v82' / 'compose.py')
garments = importlib.util.module_from_spec(garments_spec)
garments_spec.loader.exec_module(garments)
html = garments.extend(html, root)
orbit_spec = importlib.util.spec_from_file_location('tgm_orbit_v824_compose', root / 'orbit-v824' / 'compose.py')
orbit = importlib.util.module_from_spec(orbit_spec)
orbit_spec.loader.exec_module(orbit)
html = orbit.extend(html, root)
brand_spec = importlib.util.spec_from_file_location('tgm_brand_mgm_compose', root / 'brand-mgm' / 'compose.py')
brand = importlib.util.module_from_spec(brand_spec)
brand_spec.loader.exec_module(brand)
html = brand.extend(html, root)
drag_spec = importlib.util.spec_from_file_location('tgm_acabado_drag_v827_compose', root / 'acabado-drag-v827' / 'compose.py')
drag = importlib.util.module_from_spec(drag_spec)
drag_spec.loader.exec_module(drag)
html = drag.extend(html, root)
(root.parent / 'dist' / 'index.html').write_text(html)
print('Built standalone photo studio:', len(html.encode()), 'bytes')
