/* TGM photo compositor. Fixed generated garment bases, not a cloth or fit solver.
   Asset pixels are embedded by build.py; there are no network requests. */
const PHOTO_DEFAULTS={source:'generated',side:'front',background:'studio',exposure:0,relief:100,thread:35,fabricPrint:true,final:{front:null,back:null}};
const PHOTO_BASES={
 playera:{label:'Playera · jersey',neck:'round',cuff:'simple',hem:'double',texture:'jersey',crop:{front:[36,121,733,786],back:[784,121,724,786]}},
 hoodie:{label:'Hoodie · felpa',neck:'hood',cuff:'rib',hem:'rib',texture:'fleece',crop:{front:[47,81,714,820],back:[778,83,715,820]}},
 polo:{label:'Polo · piqué',neck:'polo',cuff:'rib',hem:'double',texture:'pique',crop:{front:[23,79,739,865],back:[777,79,736,865]}}
};
const photoPrepared=new Map(),photoTintCache=new Map();
let photoFrame=0,photoTicket=0,photoDetail={view:'front',zoom:1,x:400,y:460,canvas:null},photoInitialized=false;
function ensurePhoto(){state.photo={...PHOTO_DEFAULTS,...state.photo,final:{...PHOTO_DEFAULTS.final,...state.photo?.final}};return state.photo}
function photoBaseDefaults(){const b=PHOTO_BASES[state.garment];state.neck=b.neck;state.cuff=b.cuff;state.hem=b.hem;state.texture=b.texture;if(state.garment==='hoodie'){state.hood.drawstring=true;state.hood.pocket=true}state.pro.fit='regular';state.pro.length=100;state.pro.sleeve=100}
function photoMismatchReasons(){const b=PHOTO_BASES[state.garment],r=[];if(state.neck!==b.neck)r.push('cuello');if(state.cuff!==b.cuff)r.push('puño');if(state.hem!==b.hem)r.push('dobladillo');if(state.garment==='hoodie'&&!state.hood.drawstring)r.push('sin cordón');if(state.garment==='hoodie'&&!state.hood.pocket)r.push('sin bolsillo');if(state.pro.fit!=='regular'||state.pro.length!==100||state.pro.sleeve!==100)r.push('proporciones 3D');return r}
function visualSignature(){const value=JSON.stringify([state.garment,state.bodyColor,state.contrastColor,[state.contrast.neck,state.contrast.cuff,state.contrast.hem],state.neck,state.cuff,state.hem,[state.hood.drawstring,state.hood.pocket],state.fabric,state.gsm,state.stretch,state.texture,state.pro.fit,state.pro.length,state.pro.sleeve,state.artworks.map(a=>[a.id,a.view,a.zone,a.kind,a.text,a.font,a.color,a.method,a.x,a.y,a.width,a.rotation,a.image,a.dimensions])]);let a=2166136261,b=5381;for(let i=0;i<value.length;i++){a=Math.imul(a^value.charCodeAt(i),16777619);b=Math.imul(b,33)^value.charCodeAt(i)}return (a>>>0).toString(16).padStart(8,'0')+(b>>>0).toString(16).padStart(8,'0')}
function photoIssues(views=['front','back']){const p=ensurePhoto();if(p.source==='generated'){const r=photoMismatchReasons();return r.length?['La base no representa estos cambios: '+r.join(', ')+'. Usa una confección compatible o carga renders actualizados.']:[]}const sig=visualSignature(),r=[];for(const view of views){const label=view==='front'?'frente':'espalda',item=p.final[view];if(!item)r.push('Falta cargar el render de '+label+'.');else if(item.signature!==sig)r.push('El render de '+label+' corresponde a una versión anterior del diseño. Carga su imagen actualizada.')}return r}
function assertPhotoReady(views=['front','back']){const problems=photoIssues(views);if(problems.length)throw Error(problems.join(' '))}
function photoRect(garment=state.garment,view='front'){const [, ,w,h]=PHOTO_BASES[garment].crop[view];const scale=Math.min(674/w,768/h);return {x:(W-w*scale)/2,y:(H-h*scale)/2-8,w:w*scale,h:h*scale}}
function photoZone(zone,view){const hood=state.garment==='hoodie',r=photoRect(state.garment,view);let u=.5,v=hood?.45:.37;if(zone==='back')v=hood?.44:.38;if(zone==='hem'){u=view==='front'?.65:.35;v=.91}if(zone==='leftSleeve'||zone==='rightSleeve'){const isRight=(zone==='leftSleeve')===(view==='front');u=isRight?.895:.105;v=hood?.48:.31}return {x:r.x+r.w*u,y:r.y+r.h*v,scale:r.w*(hood?.57:.59)/340}}
function photoPose(a){const source=zonePosition(a.zone,a.view),target=photoZone(a.zone,a.view);return {...a,x:target.x+(a.x-source.x)*target.scale,y:target.y+(a.y-source.y)*target.scale,width:a.width*target.scale}}
function photoPutPosition(a,x,y){const source=zonePosition(a.zone,a.view),target=photoZone(a.zone,a.view);a.x=clamp(source.x+(x-target.x)/target.scale,0,W);a.y=clamp(source.y+(y-target.y)/target.scale,0,H)}
function polygon(ctx,points){ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill()}
function photoTrimMask(garment,view,width,height,part){const c=document.createElement('canvas');c.width=width;c.height=height;const t=c.getContext('2d');t.scale(width,height);t.fillStyle='white';const front=view==='front';
 if(garment==='playera'){
  if(part==='neck'){t.beginPath();if(front){t.moveTo(.354,.007);t.bezierCurveTo(.39,.045,.587,.045,.625,.007);t.lineTo(.647,.035);t.bezierCurveTo(.665,.155,.352,.16,.335,.035)}else{t.moveTo(.357,0);t.quadraticCurveTo(.5,.045,.633,0);t.lineTo(.65,.027);t.quadraticCurveTo(.5,.074,.336,.025)}t.closePath();t.fill()}
  if(part==='cuff'){polygon(t,[[-.05,.327],[.04,.327],[.216,.401],[.216,.52],[-.05,.52]]);polygon(t,[[.78,.401],[.955,.329],[1.05,.329],[1.05,.52],[.78,.52]])}
  if(part==='hem'){t.beginPath();t.moveTo(.202,.955);t.quadraticCurveTo(.5,.974,.802,.955);t.lineTo(.8,1);t.lineTo(.195,1);t.closePath();t.fill()}
 }else if(garment==='polo'){
  if(part==='neck'){if(front){polygon(t,[[.369,-.05],[.625,-.05],[.636,.04],[.666,.129],[.647,.17],[.616,.172],[.557,.14],[.535,.156],[.483,.166],[.444,.148],[.403,.168],[.366,.165],[.33,.138],[.349,.071]])}else{t.beginPath();t.moveTo(.364,0);t.lineTo(.644,0);t.lineTo(.681,.106);t.quadraticCurveTo(.5,.155,.324,.106);t.closePath();t.fill()}}
  if(part==='cuff'){polygon(t,[[-.05,.366],[.025,.366],[.222,.432],[.225,.56],[-.05,.56]]);polygon(t,[[.776,.431],[.967,.368],[1.05,.368],[1.05,.56],[.8,.497],[.781,.464]])}
  if(part==='hem'){t.beginPath();t.moveTo(.197,.954);t.quadraticCurveTo(.5,.983,.813,.954);t.lineTo(.816,1);t.lineTo(.19,1);t.closePath();t.fill()}
 }else{
  if(part==='neck'){t.beginPath();if(front){t.moveTo(.248,.137);t.lineTo(.25,-.1);t.lineTo(.77,-.1);t.lineTo(.751,.137);t.bezierCurveTo(.699,.159,.632,.179,.57,.191);t.quadraticCurveTo(.52,.208,.48,.184);t.quadraticCurveTo(.37,.167,.248,.143)}else{t.moveTo(.255,.126);t.lineTo(.255,-.1);t.lineTo(.744,-.1);t.lineTo(.743,.129);t.bezierCurveTo(.703,.222,.64,.272,.505,.298);t.bezierCurveTo(.405,.276,.333,.216,.255,.126)}t.closePath();t.fill();if(front){t.strokeStyle='white';t.lineWidth=.023;t.lineCap='round';t.beginPath();t.moveTo(.442,.145);t.bezierCurveTo(.449,.2,.454,.28,.443,.39);t.lineTo(.445,.407);t.moveTo(.568,.146);t.bezierCurveTo(.557,.22,.568,.31,.567,.402);t.stroke()}}
  if(part==='cuff'){polygon(t,[[.015,.9],[.15,.906],[.141,.99],[.032,1]]);polygon(t,[[.852,.908],[.988,.9],[.97,1],[.857,.991]])}
  if(part==='hem'){t.beginPath();t.moveTo(.21,.9);t.quadraticCurveTo(.49,.925,.777,.903);t.lineTo(.777,1);t.lineTo(.21,1);t.closePath();t.fill()}
 }
 return c
}
async function preparePhoto(garment,view){const key=garment+':'+view;if(photoPrepared.has(key))return photoPrepared.get(key);const promise=(async()=>{const img=await getImage(PHOTO_ASSETS[garment]);const crop=PHOTO_BASES[garment].crop[view],w=crop[2],h=crop[3],c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,...crop,0,0,w,h);const pixels=x.getImageData(0,0,w,h),lum=new Float32Array(w*h);for(let i=0;i<lum.length;i++){const n=i*4;lum[i]=(pixels.data[n]*.2126+pixels.data[n+1]*.7152+pixels.data[n+2]*.0722)/255}const masks={};for(const part of ['neck','cuff','hem'])masks[part]=photoTrimMask(garment,view,w,h,part).getContext('2d').getImageData(0,0,w,h).data;return {c,w,h,pixels,lum,masks}})();photoPrepared.set(key,promise);try{return await promise}catch(e){photoPrepared.delete(key);throw e}}
async function tintedPhoto(garment,view){const p=ensurePhoto(),key=JSON.stringify([garment,view,state.bodyColor,state.contrastColor,state.contrast,state.texture,p.exposure,p.relief,p.thread]);if(photoTintCache.has(key))return photoTintCache.get(key);const src=await preparePhoto(garment,view),c=document.createElement('canvas');c.width=src.w;c.height=src.h;const x=c.getContext('2d'),out=x.createImageData(src.w,src.h),body=parseColor(state.bodyColor),contrast=parseColor(state.contrastColor),parts=['neck','cuff','hem'].filter(k=>state.contrast[k]);const exposure=Math.pow(2,p.exposure/50),relief=p.relief/100,grain=p.thread/100;for(let i=0;i<src.lum.length;i++){const n=i*4,alpha=src.pixels.data[n+3];if(!alpha)continue;let weight=0;for(const k of parts)weight=Math.max(weight,src.masks[k][n+3]/255);const xx=i%src.w,yy=Math.floor(i/src.w),noise=state.texture==='smooth'?0:state.texture==='pique'?Math.sin(xx*2.2)*Math.sin(yy*2.4)*.017:Math.sin(xx*2.1+Math.sin(yy*2.0))*.010;const value=Math.pow(Math.max(.025,src.lum[i]/.66),relief)*exposure*(1+noise*grain);for(let j=0;j<3;j++){const color=body[j]*(1-weight)+contrast[j]*weight;const sheen=(1-color/255)*8*Math.pow(src.lum[i],1.4);out.data[n+j]=clamp(color*value+sheen,0,255)}out.data[n+3]=alpha}x.putImageData(out,0,0);photoTintCache.set(key,c);while(photoTintCache.size>8)photoTintCache.delete(photoTintCache.keys().next().value);return c}
function photoSample(src,rect,x,y){const u=Math.round((x-rect.x)/rect.w*(src.w-1)),v=Math.round((y-rect.y)/rect.h*(src.h-1));if(u<0||v<0||u>=src.w||v>=src.h)return {l:.66,a:0};const i=v*src.w+u;return {l:src.lum[i],a:src.pixels.data[i*4+3]/255}}
async function photoDrawApplications(ctx,view,scale){const src=await preparePhoto(state.garment,view),rect=photoRect(state.garment,view),p=ensurePhoto();for(const a of state.artworks.filter(a=>a.view===view)){if(a.kind==='text'&&!a.text.trim()||a.kind==='image'&&!a.image)continue;const pose=photoPose(a),geom=await artGeometry(pose),angle=pose.rotation*Math.PI/180,ww=Math.abs(geom.width*Math.cos(angle))+Math.abs(geom.height*Math.sin(angle)),hh=Math.abs(geom.width*Math.sin(angle))+Math.abs(geom.height*Math.cos(angle));const x0=Math.floor(Math.max(0,pose.x-ww/2-12)*scale),y0=Math.floor(Math.max(0,pose.y-hh/2-12)*scale),w=Math.max(1,Math.ceil(Math.min(W*scale-x0,(ww+24)*scale))),h=Math.max(1,Math.ceil(Math.min(H*scale-y0,(hh+24)*scale)));const c=document.createElement('canvas');c.width=w;c.height=h;const t=c.getContext('2d',{willReadFrequently:true});t.setTransform(scale,0,0,scale,-x0,-y0);await drawArt(t,{...pose,method:a.method==='sublimation'?'print':a.method});t.setTransform(1,0,0,1,0,0);const data=t.getImageData(0,0,w,h),input=new Uint8ClampedArray(data.data);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const wx=(x+x0)/scale,wy=(y+y0)/scale,sample=photoSample(src,rect,wx,wy);const n=(y*w+x)*4;if(!sample.a){data.data[n+3]=0;continue}let sx=x,sy=y;if(p.fabricPrint){const dx=photoSample(src,rect,wx+5,wy).l-photoSample(src,rect,wx-5,wy).l,dy=photoSample(src,rect,wx,wy+5).l-photoSample(src,rect,wx,wy-5).l;sx=clamp(Math.round(x-dx*9*scale),0,w-1);sy=clamp(Math.round(y-dy*7*scale),0,h-1)}const from=(sy*w+sx)*4,light=p.fabricPrint?clamp(Math.pow(sample.l/.66,.72),.38,1.18):1;for(let j=0;j<3;j++)data.data[n+j]=input[from+j]*light;data.data[n+3]=input[from+3]*sample.a*(a.method==='sublimation'?.95:1)}t.putImageData(data,0,0);ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.globalCompositeOperation=a.method==='sublimation'?'multiply':'source-over';ctx.drawImage(c,x0,y0);ctx.restore()}}
function photoBackground(ctx,width,height,kind){if(kind==='transparent')return;const gradient=ctx.createRadialGradient(width*.5,height*.32,10,width*.5,height*.5,height*.8);gradient.addColorStop(0,kind==='dark'?'#484e5a':'#ffffff');gradient.addColorStop(1,kind==='dark'?'#20232b':kind==='white'?'#ffffff':'#e8ecf1');ctx.fillStyle=gradient;ctx.fillRect(0,0,width,height)}
async function renderPhoto(canvas,view,{edit=false,background=false,stamp=false}={}){const p=ensurePhoto(),ctx=canvas.getContext('2d'),scale=canvas.width/W;ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);if(background)photoBackground(ctx,canvas.width,canvas.height,p.source==='final'?'white':p.background);if(p.source==='final'){const item=p.final[view];if(item){const img=await getImage(item.image),s=Math.min(canvas.width*.94/img.naturalWidth,canvas.height*.87/img.naturalHeight);ctx.drawImage(img,(canvas.width-img.naturalWidth*s)/2,(canvas.height*.90-img.naturalHeight*s)/2,img.naturalWidth*s,img.naturalHeight*s)}else{ctx.fillStyle='#657089';ctx.textAlign='center';ctx.font='24px Arial';ctx.fillText('Carga el render de '+(view==='front'?'frente':'espalda'),canvas.width/2,canvas.height/2)}}else{const garment=state.garment,rect=photoRect(garment,view),image=await tintedPhoto(garment,view);ctx.save();ctx.scale(scale,scale);ctx.drawImage(image,rect.x,rect.y,rect.w,rect.h);await photoDrawApplications(ctx,view,scale);if(edit&&selected()?.view===view){const a=photoPose(selected()),g=await artGeometry(a);ctx.translate(a.x,a.y);ctx.rotate(a.rotation*Math.PI/180);ctx.strokeStyle='#5163e5';ctx.lineWidth=1.8;ctx.setLineDash([6,4]);ctx.strokeRect(-g.width/2-7,-g.height/2-7,g.width+14,g.height+14);ctx.setLineDash([]);ctx.fillStyle='white';for(const [sx,sy]of [[-1,-1],[1,-1],[-1,1],[1,1]]){ctx.fillRect(sx*(g.width/2+7)-3,sy*(g.height/2+7)-3,6,6);ctx.strokeRect(sx*(g.width/2+7)-3,sy*(g.height/2+7)-3,6,6)}}ctx.restore()}if(stamp){ctx.save();ctx.setTransform(1,0,0,1,0,0);const dark=p.source==='generated'&&p.background==='dark';ctx.fillStyle=dark?'#eef0f7':'#2b3549';ctx.textAlign='center';ctx.font='600 '+Math.round(canvas.width*.0145)+'px Arial';ctx.fillText(GARMENTS[state.garment].label.toUpperCase()+' · '+(view==='front'?'FRENTE':'ESPALDA'),canvas.width/2,canvas.height*.938);ctx.font=Math.round(canvas.width*.011)+'px Arial';ctx.fillStyle=dark?'#c3cbdb':'#647085';ctx.fillText(p.source==='final'?'Referencia de acabado · confirmar con muestra física':'Base generada · textura, color, caída y aplicación aproximados',canvas.width/2,canvas.height*.963);ctx.restore()}return canvas}
function syncPhotoUI(){if(!$('#photoStage'))return;const p=ensurePhoto();$('#photoStage').dataset.view=p.side;$('#photoStage').dataset.background=p.source==='final'?'white':p.background;$('#photoBaseName').textContent=PHOTO_BASES[state.garment].label;$('#photoOrigin').textContent=p.source==='final'?'Render cargado · revisar correspondencia con el pedido':'Base generada · apariencia aproximada';$('#photoSource').value=p.source;$('#photoGeneratedControls').hidden=p.source!=='generated';$('#photoFinalControls').hidden=p.source!=='final';$$('[data-photo]').forEach(el=>{const v=p[el.dataset.photo];if(el.type==='checkbox')el.checked=v;else el.value=v});$('#photoExposureValue').textContent=(p.exposure>0?'+':'')+p.exposure;$('#photoReliefValue').textContent=p.relief+' %';$('#photoThreadValue').textContent=p.thread+' %';$$('[data-photo-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.photoView===p.side));for(const view of ['front','back']){const item=p.final[view];$('#photoFinal'+(view==='front'?'Front':'Back')+'Info').textContent=item?item.width+' × '+item.height+' px · '+(item.signature===visualSignature()?'corresponde a esta versión':'requiere actualizar'):'PNG o JPG · hasta 10 MB'}const issues=photoIssues();$('#photoMismatch').hidden=!issues.length;$('#photoMismatchText').textContent=issues.join(' ');$('#photoUseBase').hidden=p.source!=='generated';$('#photoStatus').textContent=issues.length?'Revisar la referencia antes de exportar':p.source==='final'?'Imágenes cargadas para esta versión del diseño':'Colores y diseños editables · frente y espalda';$('#photoEdit').disabled=p.source==='final';for(const view of ['front','back'])$('#photo'+(view==='front'?'Front':'Back')).classList.toggle('editable',photoCanPlaceArt())}
function schedulePhoto(){syncPhotoUI();cancelAnimationFrame(photoFrame);const ticket=++photoTicket;photoFrame=requestAnimationFrame(async()=>{try{const canvases=[];for(const view of ['front','back']){const c=document.createElement('canvas');c.width=1000;c.height=1150;await renderPhoto(c,view,{edit:photoShowsArtChrome()});canvases.push(c)}if(ticket!==photoTicket)return;for(const [i,id]of ['#photoFront','#photoBack'].entries()){const target=$(id),x=target.getContext('2d');x.clearRect(0,0,target.width,target.height);x.drawImage(canvases[i],0,0,target.width,target.height)}if(typeof afterPhotoSheets==='function')await afterPhotoSheets(canvases);if($('#photoDetailDialog').open)await refreshPhotoDetail()}catch(e){if(ticket===photoTicket){$('#photoStatus').textContent='No se pudo preparar la referencia.';toast(e.message)}}})}
async function exportPhoto(view){assertPhotoReady([view]);const c=document.createElement('canvas');c.width=2000;c.height=2300;return renderPhoto(c,view,{background:true,stamp:true})}
function photoCanPlaceArt(){return currentTab==='art'&&ensurePhoto().source==='generated'}
function photoShowsArtChrome(){return photoCanPlaceArt()}
function photoClientPoint(rect,clientX,clientY){return {x:(clientX-rect.left)/rect.width*W,y:(clientY-rect.top)/rect.height*H}}
function photoPointer(canvas,e){return photoClientPoint(canvas.getBoundingClientRect(),e.clientX,e.clientY)}
function photoArtworkVisible(a){return !!(a&&!(a.kind==='text'&&!String(a.text||'').trim())&&!(a.kind==='image'&&!a.image))}
function photoArtworkDraggable(a){return photoArtworkVisible(a)&&!(typeof fullSublimation==='function'&&fullSublimation(a))}
function photoArtworkLocalPoint(art,point,pose){pose=pose||photoPose(art);const r=-art.rotation*Math.PI/180,dx=point.x-pose.x,dy=point.y-pose.y;return {x:dx*Math.cos(r)-dy*Math.sin(r),y:dx*Math.sin(r)+dy*Math.cos(r),dx,dy}}
function photoHitsArtworkBox(local,geom,pad=12){return Math.abs(local.x)<=geom.width/2+pad&&Math.abs(local.y)<=geom.height/2+pad}
async function photoHitArtwork(view,point){
  if(!photoCanPlaceArt())return null;
  for(const a of state.artworks.filter(item=>item.view===view).reverse()){
    if(!photoArtworkDraggable(a))continue;
    const pose=photoPose(a),geom=await artGeometry(pose),local=photoArtworkLocalPoint(a,point,pose);
    if(photoHitsArtworkBox(local,geom))return {art:a,pose,geom,local};
  }
  return null;
}
function setupPhotoDrag(canvas,view){let drag=null,activePointer=null;canvas.addEventListener('pointerdown',async e=>{if(currentTab!=='art'||ensurePhoto().source!=='generated')return;activePointer=e.pointerId;const point=photoPointer(canvas,e);canvas.focus();canvas.setPointerCapture(e.pointerId);for(const a of state.artworks.filter(a=>a.view===view).reverse()){const pose=photoPose(a),g=await artGeometry(pose);if(activePointer!==e.pointerId)return;const r=-a.rotation*Math.PI/180,dx=point.x-pose.x,dy=point.y-pose.y;if(Math.abs(dx*Math.cos(r)-dy*Math.sin(r))<=g.width/2+12&&Math.abs(dx*Math.sin(r)+dy*Math.cos(r))<=g.height/2+12){selectedArt=a.id;drag={id:a.id,dx,dy};canvas.classList.add('dragging');updateArtList();syncArt();schedulePhoto();break}}});canvas.addEventListener('pointermove',e=>{if(!drag||activePointer!==e.pointerId)return;const a=state.artworks.find(v=>v.id===drag.id);if(!a)return;const point=photoPointer(canvas,e);photoPutPosition(a,point.x-drag.dx,point.y-drag.dy);syncArt();changed()});const end=()=>{activePointer=null;drag=null;canvas.classList.remove('dragging')};for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,end);canvas.addEventListener('keydown',e=>{const a=selected();if(currentTab!=='art'||!a||a.view!==view||ensurePhoto().source!=='generated')return;const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(!d)return;e.preventDefault();const amount=e.shiftKey?10:2;a.x=clamp(a.x+d[0]*amount,0,W);a.y=clamp(a.y+d[1]*amount,0,H);syncArt();changed()})}
async function readFinalRender(file){if(file.size>10*1024*1024)throw Error('El render excede 10 MB.');const bytes=new Uint8Array(await file.arrayBuffer());const png=bytes.length>24&&bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71,jpeg=bytes.length>4&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(!png&&!jpeg)throw Error('Carga un PNG o JPG válido.');const src=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(Error('No se pudo leer el render.'));r.readAsDataURL(file)}),img=await getImage(src);if(img.naturalWidth*img.naturalHeight>25000000||img.naturalWidth<200||img.naturalHeight<200)throw Error('Usa un render de al menos 200 × 200 px y máximo 25 megapíxeles.');const c=document.createElement('canvas'),ratio=Math.min(1,3000/Math.max(img.naturalWidth,img.naturalHeight));c.width=Math.round(img.naturalWidth*ratio);c.height=Math.round(img.naturalHeight*ratio);c.getContext('2d').drawImage(img,0,0,c.width,c.height);const image=c.toDataURL('image/png');if(image.length>14000000)throw Error('La imagen convertida es demasiado pesada; exporta un PNG más pequeño.');return {image,width:c.width,height:c.height}}
async function validatePhoto(raw){if(raw===undefined)return {...PHOTO_DEFAULTS,final:{front:null,back:null}};if(!raw||typeof raw!=='object')throw Error('Ajustes de acabado inválidos.');const out={};for(const [key,values]of Object.entries({source:['generated','final'],side:['front','back','both','orbit'],background:['studio','white','dark','transparent']}))out[key]=oneOf(raw[key],values,key);for(const [key,min,max]of [['exposure',-20,20],['relief',50,130],['thread',0,100]])out[key]=numeric(raw[key],min,max,key);out.fabricPrint=boolean(raw.fabricPrint,'adaptación a pliegues');out.final={front:null,back:null};for(const view of ['front','back']){const item=raw.final?.[view];if(item==null)continue;if(typeof item!=='object')throw Error('Render inválido.');const image=safeString(item.image,14000000,'render');if(!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(image))throw Error('Formato de render inválido.');const header=atob(image.split(',')[1].slice(0,44)),width=((header.charCodeAt(16)<<24)>>>0)+(header.charCodeAt(17)<<16)+(header.charCodeAt(18)<<8)+header.charCodeAt(19),height=((header.charCodeAt(20)<<24)>>>0)+(header.charCodeAt(21)<<16)+(header.charCodeAt(22)<<8)+header.charCodeAt(23);if(header.slice(1,4)!=='PNG'||width<200||height<200||width>3000||height>3000)throw Error('Dimensiones de render inválidas.');const img=await getImage(image);if(img.naturalWidth!==width||img.naturalHeight!==height)throw Error('Render dañado.');const signature=safeString(item.signature,16,'versión del render');if(!/^[a-f0-9]{16}$/.test(signature))throw Error('Versión de render inválida.');out.final[view]={image,width,height,signature}}return out}
async function refreshPhotoDetail(){const ticket=photoDetail.ticket=(photoDetail.ticket||0)+1,view=photoDetail.view,c=document.createElement('canvas');c.width=2000;c.height=2300;await renderPhoto(c,view);if(ticket!==photoDetail.ticket||view!==photoDetail.view)return;photoDetail.canvas=c;paintPhotoDetail()}
function paintPhotoDetail(){const c=$('#detailCanvas'),r=c.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);if(r.width>0&&r.height>0){const w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(c.width!==w)c.width=w;if(c.height!==h)c.height=h}const x=c.getContext('2d');x.setTransform(1,0,0,1,0,0);x.fillStyle='#edf0f4';x.fillRect(0,0,c.width,c.height);if(!photoDetail.canvas)return;const base=Math.min(c.width/W,c.height/H),s=base*photoDetail.zoom;x.drawImage(photoDetail.canvas,c.width/2-photoDetail.x*s,c.height/2-photoDetail.y*s,W*s,H*s);$('#detailZoom').textContent=Math.round(photoDetail.zoom*100)+' %'}
async function openPhotoDetail(preset){photoDetail.view=ensurePhoto().side==='back'?'back':'front';photoDetail.zoom=preset?2.5:1;photoDetail.x=400;photoDetail.y=preset==='neck'?230:preset==='fabric'?430:preset==='hem'?735:460;$('#detailView').value=photoDetail.view;$('#photoDetailDialog').showModal();await refreshPhotoDetail()}
function setupPhotoDetail(){window.addEventListener('resize',()=>{if($('#photoDetailDialog').open)paintPhotoDetail()});const c=$('#detailCanvas'),pointers=new Map();let last=null,distance=null;const changeZoom=factor=>{photoDetail.zoom=clamp(photoDetail.zoom*factor,1,4);paintPhotoDetail()};$('#detailPlus').addEventListener('click',()=>changeZoom(1.3));$('#detailMinus').addEventListener('click',()=>changeZoom(1/1.3));$('#detailFit').addEventListener('click',()=>{Object.assign(photoDetail,{zoom:1,x:400,y:460});paintPhotoDetail()});$('#detailView').addEventListener('change',async e=>{photoDetail.view=e.target.value;await refreshPhotoDetail()});c.addEventListener('wheel',e=>{e.preventDefault();changeZoom(Math.exp(-e.deltaY*.0015))},{passive:false});c.addEventListener('pointerdown',e=>{c.focus();c.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);last=[e.clientX,e.clientY]});c.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]);if(distance)changeZoom(d/distance);distance=d}else if(last){const r=c.getBoundingClientRect(),base=Math.min(c.width/W,c.height/H)*photoDetail.zoom;photoDetail.x=clamp(photoDetail.x-(e.clientX-last[0])*c.width/r.width/base,0,W);photoDetail.y=clamp(photoDetail.y-(e.clientY-last[1])*c.height/r.height/base,0,H);paintPhotoDetail()}last=[e.clientX,e.clientY]});for(const type of ['pointerup','pointercancel','lostpointercapture'])c.addEventListener(type,e=>{pointers.delete(e.pointerId);last=null;distance=null});c.addEventListener('keydown',e=>{const actions={'+':()=>changeZoom(1.2),'=':()=>changeZoom(1.2),'-':()=>changeZoom(1/1.2),ArrowLeft:()=>photoDetail.x=clamp(photoDetail.x-20,0,W),ArrowRight:()=>photoDetail.x=clamp(photoDetail.x+20,0,W),ArrowUp:()=>photoDetail.y=clamp(photoDetail.y-20,0,H),ArrowDown:()=>photoDetail.y=clamp(photoDetail.y+20,0,H)};if(actions[e.key]){e.preventDefault();actions[e.key]();paintPhotoDetail()}})}
function initPhoto(){if(photoInitialized)return;photoInitialized=true;ensurePhoto();$$('[data-photo-view]').forEach(b=>b.addEventListener('click',()=>{state.photo.side=b.dataset.photoView;changed()}));$('#photoOpenSettings').addEventListener('click',()=>tab('photo'));$('#photoEdit').addEventListener('click',()=>{tab('art');if(!state.artworks.length)addArt()});$('#photoDetail').addEventListener('click',()=>busy($('#photoDetail'),()=>openPhotoDetail()));$$('[data-detail]').forEach(b=>b.addEventListener('click',()=>busy(b,()=>openPhotoDetail(b.dataset.detail))));$('#photoUseBase').addEventListener('click',()=>{photoBaseDefaults();populate();changed()});$$('[data-photo]').forEach(el=>el.addEventListener(el.type==='range'?'input':'change',()=>{state.photo[el.dataset.photo]=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;changed()}));$('#photoSource').addEventListener('change',e=>{state.photo.source=e.target.value;setWorkspace('photo',false);changed()});for(const view of ['front','back'])$('#photoFinal'+(view==='front'?'Front':'Back')).addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;const order=state,sig=visualSignature();try{const item=await readFinalRender(file);if(state!==order||visualSignature()!==sig)throw Error('El pedido cambió durante la carga; vuelve a cargar la imagen.');state.photo.final[view]={...item,signature:sig};state.photo.source='final';state.photo.side=view;changed();toast('Render integrado al pedido.')}catch(error){toast(error.message)}});setupPhotoDrag($('#photoFront'),'front');setupPhotoDrag($('#photoBack'),'back');setupPhotoDetail();schedulePhoto()}
